/**
 * Crystal name triples: AmharicScript|RomanizedAmharic|EnglishMeaning
 *
 * Middle segment = Amharic written with English letters (romanization),
 * not the Latin language.
 *
 * Keys are letterCore() forms (lowercase a-z only) or productIdentity ids.
 *
 * Anti-overcorrection:
 * - Prefer operator product knowledge over linguistic guesses.
 * - If exact English is unknown for a local name, use the name itself
 *   (e.g. Akezha|Akezha), do not invent a gloss.
 * - See scripts/lib/crystalNameOperatorLocks.mjs for frozen operator decisions.
 */

import { recommendedCoresToByCore } from "./crystalNameRecommendedAdditions.mjs";

/** @typedef {{ am: string, rom: string, en: string }} CrystalTriple */

/** @type {Record<string, CrystalTriple>} */
export const BY_IDENTITY = {
  shiro_food: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  shiro_bakela: { am: "የሽሮ ባቄላ", rom: "Ye Shero Bakela", en: "Fava bean shiro" },
  shiro_ater: { am: "የሽሮ አተር", rom: "Ye Shero Ater", en: "Pea shiro" },
  shiro_mtn: { am: "ምትን ሽሮ", rom: "Mtn Shero", en: "Mtn shiro" },
  shbo_cleaning: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  fish_fillet: { am: "የአሳ ፍሌት", rom: "Ye Asa Filet", en: "Fish fillet" },
  selit_ingredient: { am: "ሰሊጥ", rom: "Selit", en: "Sesame seed" },
  kosta_food: { am: "ቆስጣ", rom: "Kosta", en: "Ethiopian kale" },
  pasta_food: { am: "ፓስታ", rom: "Pasta", en: "Pasta" },
  posta_packaging: { am: "ፖስታ", rom: "Posta", en: "Postage / packaging posta" },
  wheat_flour: { am: "የስንዴ ዱቄት", rom: "Ye Sinde Duket", en: "Wheat flour" },
  white_flour: { am: "ነጭ ዱቄት", rom: "Nech Duket", en: "White flour" },
  keberete_flame: { am: "ከበረት", rom: "Keberet", en: "Keberet" },
  coffee_drink: { am: "ቡና", rom: "Buna", en: "Coffee" },
  coffee_powder: { am: "የቡና ዱቄት", rom: "Ye Buna Duket", en: "Coffee powder" },
  coffee_cup: { am: "የቡና ስኒ", rom: "Ye Buna Sini", en: "Coffee cup" },
  addis_tea: { am: "አዲስ ሻይ", rom: "Addis Shay", en: "Addis tea" },
  addis_tea_bag: { am: "አዲስ የሻይ ከረጢት", rom: "Addis Ye Shay Keretit", en: "Addis tea bag" },
  pump: { am: "ፓምፕ", rom: "Pump", en: "Pump" },
  lamp: { am: "ላምፕ", rom: "Lamp", en: "Lamp" },
  lewuz_peanut: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  straw_drinking: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  estracho_item: { am: "ኤስትራቾ", rom: "Estracho", en: "Estracho" },
  garlic_bulb: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  white_onion: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "White onion" },
  soft_tissue: { am: "ሶፍት", rom: "Soft", en: "Soft tissue paper" },
  tomato_paste: { am: "የቲማቲም ፔስት", rom: "Ye Timatim Pest", en: "Tomato paste" },
  tomato_pasta: { am: "የቲማቲም ፓስታ", rom: "Ye Timatim Pasta", en: "Tomato pasta" },
  pepsi_drink: { am: "ፔፕሲ", rom: "Pepsi", en: "Pepsi soft drink" },
  h20_abrasive: { am: "ኤች2ኦፒ አብሬሲቭ", rom: "H2OP Abrasive", en: "H2OP abrasive" },
  h20_proof_ampole: { am: "ኤች2ኦፒ አምፖል", rom: "H2OP Ampole", en: "H2OP waterproof bulb" },
  esteplar_shbo: { am: "ኤስቴፕላር ሽቦ", rom: "Esteplar Shbo", en: "Esteplar shbo" },
};

/**
 * letterCore → triple. Many aliases point at the same meaning.
 * Prefer careful Ethiopian inventory meanings over loose guesses.
 * @type {Record<string, CrystalTriple>}
 */
export const BY_CORE = {
  // Breads & staples
  dabo: { am: "ዳቦ", rom: "Dabo", en: "Bread" },
  bread: { am: "ዳቦ", rom: "Dabo", en: "Bread" },
  bergerdabo: { am: "በርገር ዳቦ", rom: "Berger Dabo", en: "Burger bun" },
  enjera: { am: "እንጀራ", rom: "Injera", en: "Sourdough flatbread" },
  injera: { am: "እንጀራ", rom: "Injera", en: "Sourdough flatbread" },
  anbaza: { am: "አንባሻ", rom: "Ambasha", en: "Celebration bread" },
  ambaza: { am: "አንባሻ", rom: "Ambasha", en: "Celebration bread" },
  fishambaza: { am: "የአሳ አንባሻ", rom: "Ye Asa Ambasha", en: "Fish ambasha" },
  kocho: { am: "ቆጮ", rom: "Kocho", en: "Enset bread" },
  bula: { am: "ቡላ", rom: "Bula", en: "Enset starch flour" },
  qinche: { am: "ቅንጬ", rom: "Qinche", en: "Cracked wheat" },
  knche: { am: "ቅንጬ", rom: "Qinche", en: "Cracked wheat" },
  kolo: { am: "ቆሎ", rom: "Kolo", en: "Roasted grain snack" },
  besobela: { am: "በሶ በላ", rom: "Beso Bela", en: "Beso Bela" },
  fendisha: { am: "ፈንዲሻ", rom: "Fendisha", en: "Popcorn" },
  teff: { am: "ጤፍ", rom: "Teff", en: "Teff grain" },
  tefe: { am: "ጤፍ", rom: "Teff", en: "Teff grain" },
  tafe: { am: "ጤፍ", rom: "Teff", en: "Teff grain" },
  keyteff: { am: "ቀይ ጤፍ", rom: "Key Teff", en: "Red teff" },
  teffcoustomer: { am: "የደንበኛ ጤፍ", rom: "Ye Denbeña Teff", en: "Customer teff" },

  // Spices & seasonings
  shero: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  shiro: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  shro: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  shrostaff: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  shrokitchen: { am: "ሽሮ", rom: "Shero", en: "Chickpea flour / shiro" },
  yeshrobakela: { am: "የሽሮ ባቄላ", rom: "Ye Shero Bakela", en: "Fava bean shiro" },
  yeshroater: { am: "የሽሮ አተር", rom: "Ye Shero Ater", en: "Pea shiro" },
  mtnshro: { am: "ምትን ሽሮ", rom: "Mtn Shero", en: "Mtn shiro" },
  berbere: { am: "በርበሬ", rom: "Berbere", en: "Red spice blend" },
  berebera: { am: "በርበሬ", rom: "Berbere", en: "Red spice blend" },
  kondoberbera: { am: "ቁንዶ በርበሬ", rom: "Kundo Berbere", en: "Bird's eye chili" },
  qendoberbere: { am: "ቁንዶ በርበሬ", rom: "Kundo Berbere", en: "Bird's eye chili" },
  blackkundo: { am: "ጥቁር ቁንዶ", rom: "Tikur Kundo", en: "Black bird's eye chili" },
  nechkundoberebera: { am: "ነጭ ቁንዶ በርበሬ", rom: "Nech Kundo Berbere", en: "White kundo berbere" },
  tekurekundoberebra: { am: "ጥቁር ቁንዶ በርበሬ", rom: "Tikur Kundo Berbere", en: "Black kundo berbere" },
  mitmita: { am: "ሚጥሚጣ", rom: "Mitmita", en: "Hot chili spice" },
  mitmitakariya: { am: "ሚጥሚጣ ቃሪያ", rom: "Mitmita Kariya", en: "Mitmita chili" },
  kariya: { am: "ቃሪያ", rom: "Kariya", en: "Green chili" },
  karya: { am: "ቃሪያ", rom: "Kariya", en: "Green chili" },
  kary: { am: "ቃሪያ", rom: "Kariya", en: "Green chili" },
  chlikareya: { am: "ቺሊ ቃሪያ", rom: "Chili Kariya", en: "Chili pepper" },
  yeferenjekariya: { am: "የፈረንጅ ቃሪያ", rom: "Ye Ferenj Kariya", en: "Imported chili" },
  kariyastaff: { am: "ቃሪያ", rom: "Kariya", en: "Green chili (staff)" },
  chillypowder: { am: "የቺሊ ዱቄት", rom: "Ye Chili Duket", en: "Chili powder" },
  korerima: { am: "ኮረሪማ", rom: "Korerima", en: "Ethiopian cardamom" },
  tikurazmud: { am: "ጥቁር አዝሙድ", rom: "Tikur Azmud", en: "Black cumin" },
  nechazmud: { am: "ነጭ አዝሙድ", rom: "Nech Azmud", en: "White cumin / caraway" },
  abesh: { am: "አብሽ", rom: "Abish", en: "Fenugreek" },
  abeshe: { am: "አብሽ", rom: "Abish", en: "Fenugreek" },
  telba: { am: "ተልባ", rom: "Telba", en: "Flaxseed" },
  teleba: { am: "ተልባ", rom: "Telba", en: "Flaxseed" },
  suf: { am: "ሱፍ", rom: "Suf", en: "Niger seed" },
  sufe: { am: "ሱፍ", rom: "Suf", en: "Niger seed" },
  selit: { am: "ሰሊጥ", rom: "Selit", en: "Sesame seed" },
  erd: { am: "ኤርድ", rom: "Erd", en: "Turmeric" },
  ered: { am: "ኤርድ", rom: "Erd", en: "Turmeric" },
  mekelesha: { am: "መቀለሻ", rom: "Mekelesha", en: "Finishing spice blend" },
  hellkmem: { am: "ሁሉ ቅመም", rom: "Hulu Kimem", en: "Mixed spice" },
  shaykmem: { am: "የሻይ ቅመም", rom: "Ye Shay Kimem", en: "Tea spice" },
  kamun: { am: "ከሙን", rom: "Kamun", en: "Cumin" },
  kirinfud: { am: "ቅርንፉድ", rom: "Kirinfud", en: "Clove" },
  kerefa: { am: "ቀረፋ", rom: "Kerefa", en: "Cinnamon" },
  tosegn: { am: "ጦስኝ", rom: "Tosign", en: "Tosign herb" },
  koseret: { am: "ኮሰረት", rom: "Koseret", en: "Koseret herb" },
  tenadame: { am: "ጤና አዳም", rom: "Tena Adam", en: "Rue" },
  qetema: { am: "ቀጤማ", rom: "Qetema", en: "Sedge grass / rush" },
  qetemma: { am: "ቀጤማ", rom: "Qetema", en: "Sedge grass / rush" },
  sedgegrass: { am: "ቀጤማ", rom: "Qetema", en: "Sedge grass / rush" },
  etan: { am: "እጣን", rom: "Etan", en: "Incense" },
  etane: { am: "እጣን", rom: "Etan", en: "Incense" },
  yeetaneka: { am: "የእጣን እቃ", rom: "Ye Etan Eka", en: "Incense holder" },
  // True snack-mix spice (ጨውዛ) — keep separate from lewuz/peanut
  chewza: { am: "ጨውዛ", rom: "Chewza", en: "Snack mix spice" },
  chawza: { am: "ጨውዛ", rom: "Chewza", en: "Snack mix spice" },
  mustard: { am: "ሰናፍጭ", rom: "Senafich", en: "Mustard" },
  vanilla: { am: "ቫኒላ", rom: "Vanilla", en: "Vanilla" },
  vanillaliquid: { am: "ፈሳሽ ቫኒላ", rom: "Fesash Vanilla", en: "Vanilla liquid" },
  vanillapowder: { am: "የቫኒላ ዱቄት", rom: "Ye Vanilla Duket", en: "Vanilla powder" },

  // Produce
  onion: { am: "ሽንኩርት", rom: "Shenkurt", en: "Onion" },
  shenkuret: { am: "ሽንኩርት", rom: "Shenkurt", en: "Onion" },
  keyshnkurt: { am: "ቀይ ሽንኩርት", rom: "Key Shenkurt", en: "Red onion" },
  keyshnkurtstaff: { am: "ቀይ ሽንኩርት", rom: "Key Shenkurt", en: "Red onion (staff)" },
  nechshenkuret: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "White onion" },
  nechshenkurte: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "White onion" },
  nechsenkuret: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "White onion" },
  baroshenkuret: { am: "ባሮ ሽንኩርት", rom: "Baro Shenkurt", en: "Baro Shenkurt" },
  gradiawhiteonion: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "White onion" },
  garlic: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  garlicstaff: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  chingiya: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  chinigiya: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  nechshengurt: { am: "ነጭ ሽንኩርት", rom: "Nech Shenkurt", en: "Garlic" },
  ginger: { am: "ዝንጅብል", rom: "Zinjibil", en: "Ginger" },
  gingerstaff: { am: "ዝንጅብል", rom: "Zinjibil", en: "Ginger (staff)" },
  zenjebel: { am: "ዝንጅብል", rom: "Zinjibil", en: "Ginger" },
  potato: { am: "ድንች", rom: "Dinich", en: "Potato" },
  potatoes: { am: "ድንች", rom: "Dinich", en: "Potato" },
  potatostaff: { am: "ድንች", rom: "Dinich", en: "Potato (staff)" },
  skuardnch: { am: "ስኳር ድንች", rom: "Sukar Dinich", en: "Sweet potato" },
  tomato: { am: "ቲማቲም", rom: "Timatim", en: "Tomato" },
  tomatostaff: { am: "ቲማቲም", rom: "Timatim", en: "Tomato (staff)" },
  tomatopeste: { am: "የቲማቲም ፔስት", rom: "Ye Timatim Pest", en: "Tomato paste" },
  tomatopest: { am: "የቲማቲም ፔስት", rom: "Ye Timatim Pest", en: "Tomato paste" },
  tomatopaste: { am: "የቲማቲም ፔስት", rom: "Ye Timatim Pest", en: "Tomato paste" },
  // "Tomato Pasta" is a distinct item from tomato paste (operator confirmation)
  tomatopasta: { am: "የቲማቲም ፓስታ", rom: "Ye Timatim Pasta", en: "Tomato pasta" },
  carrot: { am: "ካሮት", rom: "Karot", en: "Carrot" },
  carote: { am: "ካሮት", rom: "Karot", en: "Carrot" },
  carrotstaff: { am: "ካሮት", rom: "Karot", en: "Carrot (staff)" },
  lemon: { am: "ሎሚ", rom: "Lomi", en: "Lemon" },
  lomi: { am: "ሎሚ", rom: "Lomi", en: "Lemon" },
  banana: { am: "ሙዝ", rom: "Muz", en: "Banana" },
  benane: { am: "ሙዝ", rom: "Muz", en: "Banana" },
  avocado: { am: "አቮካዶ", rom: "Avocado", en: "Avocado" },
  yebselavocado: { am: "የበሰለ አቮካዶ", rom: "Ye Besele Avocado", en: "Ripe avocado" },
  mango: { am: "ማንጎ", rom: "Mango", en: "Mango" },
  mangoapple: { am: "ማንጎ አፕል", rom: "Mango Apple", en: "Mango apple" },
  papaya: { am: "ፓፓያ", rom: "Papaya", en: "Papaya" },
  papay: { am: "ፓፓያ", rom: "Papaya", en: "Papaya" },
  gomen: { am: "ጎመን", rom: "Gomen", en: "Collard greens" },
  gomenzer: { am: "የጎመን ዘር", rom: "Ye Gomen Zer", en: "Cabbage seed" },
  abebagomen: { am: "አበባ ጎመን", rom: "Abeba Gomen", en: "Cauliflower" },
  tekelgomen: { am: "ጥቅል ጎመን", rom: "Tikil Gomen", en: "Cabbage" },
  tekelgomenstaff: { am: "ጥቅል ጎመን", rom: "Tikil Gomen", en: "Cabbage (staff)" },
  yehabeshagomen: { am: "የሐበሻ ጎመን", rom: "Ye Habesha Gomen", en: "Ethiopian greens" },
  roundcabage: { am: "ክብ ጎመን", rom: "Kib Gomen", en: "Round cabbage" },
  borokoli: { am: "ብሮኮሊ", rom: "Brokoli", en: "Broccoli" },
  selata: { am: "ሰላጣ", rom: "Selata", en: "Lettuce / salad greens" },
  slata: { am: "ሰላጣ", rom: "Selata", en: "Lettuce / salad greens" },
  chayenaselata: { am: "ቻይና ሰላጣ", rom: "China Selata", en: "Chinese cabbage" },
  bekolo: { am: "በቆሎ", rom: "Bekolo", en: "Corn / maize" },
  bekolodukate: { am: "የበቆሎ ዱቄት", rom: "Ye Bekolo Duket", en: "Corn flour" },
  cornflour: { am: "የበቆሎ ዱቄት", rom: "Ye Bekolo Duket", en: "Corn flour" },
  sweetcorn: { am: "ጣፋጭ በቆሎ", rom: "Tafach Bekolo", en: "Sweet corn" },
  fosoliya: { am: "ፎሶሊያ", rom: "Fasoliya", en: "Green beans" },
  aterkeke: { am: "አተር ክክ", rom: "Ater Kik", en: "Split peas" },
  aterkik: { am: "አተር ክክ", rom: "Ater Kik", en: "Split peas" },
  defenmeser: { am: "ድፍን ምስር", rom: "Defen Misir", en: "Whole lentils" },
  meserkeke: { am: "ምስር ክክ", rom: "Misir Kik", en: "Split lentils" },
  yefulbakela: { am: "የፉል ባቀላ", rom: "Ye Ful Bakela", en: "Fava beans" },
  hababe: { am: "ሐባብ", rom: "Habab", en: "Melon" },
  keysirstaff: { am: "ቀይ ስር", rom: "Key Sir", en: "Beetroot (staff)" },
  keyesere: { am: "ቀይ ስር", rom: "Key Sir", en: "Beetroot" },
  perseli: { am: "ፐርስሊ", rom: "Perseli", en: "Parsley" },
  saleri: { am: "ሴለሪ", rom: "Selery", en: "Celery" },
  mushroom: { am: "እንጉዳይ", rom: "Enguday", en: "Mushroom" },
  peanuthbutter: { am: "የለውዝ ቅቤ", rom: "Ye Lewuz Kibe", en: "Peanut butter" },
  peanutbetterlewuz: { am: "የለውዝ ቅቤ", rom: "Ye Lewuz Kibe", en: "Peanut butter" },
  // gewuze / lewuze / ocholoni are the same peanut/nut as lewuz (not chewza)
  lewuz: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  lewuze: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  lewz: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  gewuze: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  gewuz: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  geuze: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  gawuze: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  peanut: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  peanuts: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  ocholoni: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  ocholony: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  ocholonyewz: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  ocholonilewz: { am: "ለውዝ", rom: "Lewuz", en: "Peanut / nut" },
  moringa: { am: "ሞሪንጋ", rom: "Moringa", en: "Moringa" },
  rozemeri: { am: "ሮዝሜሪ", rom: "Rosemary", en: "Rosemary" },

  // Proteins
  meat: { am: "ስጋ", rom: "Sega", en: "Meat" },
  meet: { am: "ስጋ", rom: "Sega", en: "Meat" },
  chicken: { am: "ዶሮ", rom: "Doro", en: "Chicken" },
  doro: { am: "ዶሮ", rom: "Doro", en: "Chicken" },
  dero: { am: "ዶሮ", rom: "Doro", en: "Chicken" },
  goat: { am: "ፍየል", rom: "Fiyel", en: "Goat" },
  goot: { am: "ፍየል", rom: "Fiyel", en: "Goat" },
  asa: { am: "አሳ", rom: "Asa", en: "Fish" },
  flite: { am: "ፍሌት", rom: "Filet", en: "Fish fillet" },
  fishfilit: { am: "የአሳ ፍሌት", rom: "Ye Asa Filet", en: "Fish fillet" },
  fletasa: { am: "ፍሌት አሳ", rom: "Filet Asa", en: "Fish fillet" },
  fishkoroso: { am: "የአሳ ቆርሶ", rom: "Ye Asa Korso", en: "Fish steak cut" },
  korso: { am: "ቆርሶ", rom: "Korso", en: "Steak cut" },
  fishnileparch: { am: "የናይል ፐርች", rom: "Ye Nile Perch", en: "Nile perch" },
  nayelperch: { am: "ናይል ፐርች", rom: "Nile Perch", en: "Nile perch" },
  tuna: { am: "ቱና", rom: "Tuna", en: "Tuna" },
  tunasmall: { am: "ቱና", rom: "Tuna", en: "Tuna (small)" },
  egg: { am: "እንቁላል", rom: "Enqulal", en: "Egg" },
  ayeb: { am: "አይብ", rom: "Ayib", en: "Ethiopian cottage cheese" },
  ayebe: { am: "አይብ", rom: "Ayib", en: "Ethiopian cottage cheese" },
  beefnormal: { am: "መደበኛ የበሬ ስጋ", rom: "Medebeña Ye Bere Sega", en: "Normal beef" },
  beefmortadela: { am: "የበሬ ሞርታዴላ", rom: "Ye Bere Mortadella", en: "Beef mortadella" },
  beefmortadellacheese: {
    am: "የበሬ ሞርታዴላ ቺዝ",
    rom: "Ye Bere Mortadella Cheese",
    en: "Beef mortadella with cheese",
  },
  beefmortadellamozerellachesse: {
    am: "የበሬ ሞርታዴላ ሞዘሬላ",
    rom: "Ye Bere Mortadella Mozzarella",
    en: "Beef mortadella with mozzarella",
  },
  beregercheese: { am: "በርገር ቺዝ", rom: "Berger Cheese", en: "Burger cheese" },
  mozerellachesse: { am: "ሞዘሬላ ቺዝ", rom: "Mozzarella Cheese", en: "Mozzarella cheese" },

  // Dairy, oils, sweeteners
  milk: { am: "ወተት", rom: "Wetet", en: "Milk" },
  keba: { am: "ቅቤ", rom: "Kibe", en: "Butter" },
  kiba: { am: "ቅቤ", rom: "Kibe", en: "Butter" },
  kebalekichen: { am: "የኩሽና ቅቤ", rom: "Ye Kushina Kibe", en: "Kitchen butter" },
  yewetkbe: { am: "የውጥ ቅቤ", rom: "Ye Wet Kibe", en: "Spiced butter" },
  shortingbutter: { am: "ሾርትኒንግ ቅቤ", rom: "Shortening Butter", en: "Shortening butter" },
  oil: { am: "ዘይት", rom: "Zeyt", en: "Oil" },
  zeyt: { am: "ዘይት", rom: "Zeyt", en: "Oil" },
  cookingoil: { am: "የማብሰያ ዘይት", rom: "Ye Mabseya Zeyt", en: "Cooking oil" },
  palmoil: { am: "የፓልም ዘይት", rom: "Ye Palm Zeyt", en: "Palm oil" },
  sunfloweroil: { am: "የሱፍ አበባ ዘይት", rom: "Ye Suf Abeba Zeyt", en: "Sunflower oil" },
  oilkg: { am: "ዘይት", rom: "Zeyt", en: "Oil" },
  oilliter: { am: "ዘይት", rom: "Zeyt", en: "Oil" },
  oli: { am: "ዘይት", rom: "Zeyt", en: "Oil" },
  honey: { am: "ማር", rom: "Mar", en: "Honey" },
  honney: { am: "ማር", rom: "Mar", en: "Honey" },
  hony: { am: "ማር", rom: "Mar", en: "Honey" },
  honye: { am: "ማር", rom: "Mar", en: "Honey" },
  yebrzmar: { am: "የብርዝ ማር", rom: "Ye Briz Mar", en: "Hive honey" },
  sugar: { am: "ስኳር", rom: "Sukar", en: "Sugar" },
  suger: { am: "ስኳር", rom: "Sukar", en: "Sugar" },
  salt: { am: "ጨው", rom: "Chew", en: "Salt" },
  rawsalt: { am: "ጥሬ ጨው", rom: "Tire Chew", en: "Raw salt" },
  saltraw: { am: "ጥሬ ጨው", rom: "Tire Chew", en: "Raw salt" },
  iodinsalt: { am: "አዮዲን ጨው", rom: "Iodin Chew", en: "Iodized salt" },
  saltiodin: { am: "አዮዲን ጨው", rom: "Iodin Chew", en: "Iodized salt" },
  tablesalte: { am: "የጠረጴዛ ጨው", rom: "Ye Terepeza Chew", en: "Table salt" },
  yemegbchewuiodi: { am: "የምግብ ጨው አዮዲን", rom: "Ye Migb Chew Iodin", en: "Iodized food salt" },
  yemegebchewiodn: { am: "የምግብ ጨው አዮዲን", rom: "Ye Migb Chew Iodin", en: "Iodized food salt" },
  yeast: { am: "እርሾ", rom: "Irsho", en: "Yeast" },
  yesetirsho: { am: "እርሾ", rom: "Irsho", en: "Yeast" },
  bakingpowder: { am: "ቤኪንግ ፓውደር", rom: "Baking Powder", en: "Baking powder" },
  breadimprover: { am: "የዳቦ ማሻሻያ", rom: "Ye Dabo Mashashaya", en: "Bread improver" },
  bakemate: { am: "ቤክሜት", rom: "Bake Mate", en: "Bake mate" },

  // Flours & powders
  flour: { am: "ዱቄት", rom: "Duket", en: "Flour" },
  flore: { am: "ዱቄት", rom: "Duket", en: "Flour" },
  duket: { am: "ዱቄት", rom: "Duket", en: "Flour" },
  finodukate: { am: "ፊኖ ዱቄት", rom: "Fino Duket", en: "Fine flour" },
  finoflore: { am: "ፊኖ ዱቄት", rom: "Fino Duket", en: "Fine flour" },
  maziflour: { am: "ማዚ ዱቄት", rom: "Mazi Duket", en: "Maize flour" },
  oats: { am: "ኦትስ", rom: "Oats", en: "Oats" },
  whiteoats: { am: "ነጭ ኦትስ", rom: "Nech Oats", en: "White oats" },
  rice: { am: "ሩዝ", rom: "Ruz", en: "Rice" },
  ruz: { am: "ሩዝ", rom: "Ruz", en: "Rice" },
  localrice: { am: "አገርሽ ሩዝ", rom: "Ageresh Ruz", en: "Local rice" },
  riceleteff: { am: "ከጤፍ ጋር ሩዝ", rom: "Ke Teff Gar Ruz", en: "Rice with teff" },
  pasta: { am: "ፓስታ", rom: "Pasta", en: "Pasta" },
  macaroni: { am: "መኮረኒ", rom: "Mekoreni", en: "Macaroni" },
  mekoreni: { am: "መኮረኒ", rom: "Mekoreni", en: "Macaroni" },
  kosta: { am: "ቆስጣ", rom: "Kosta", en: "Ethiopian kale" },
  juicepowder: { am: "የጭማቂ ዱቄት", rom: "Ye Chimaki Duket", en: "Juice powder" },
  cacawapowder: { am: "የኮኮዋ ዱቄት", rom: "Ye Kokowa Duket", en: "Cocoa powder" },
  cacawu: { am: "ኮኮዋ", rom: "Kokowa", en: "Cocoa" },
  cocawa: { am: "ኮኮዋ", rom: "Kokowa", en: "Cocoa" },
  kaokao: { am: "ኮኮዋ", rom: "Kokowa", en: "Cocoa" },
  cornfelax: { am: "ኮርን ፍሌክስ", rom: "Corn Flakes", en: "Corn flakes" },
  korenfelex: { am: "ኮርን ፍሌክስ", rom: "Corn Flakes", en: "Corn flakes" },

  // Coffee / tea / drinks
  coffee: { am: "ቡና", rom: "Buna", en: "Coffee" },
  coffe: { am: "ቡና", rom: "Buna", en: "Coffee" },
  yebunasini: { am: "የቡና ስኒ", rom: "Ye Buna Sini", en: "Coffee cup" },
  coffecup: { am: "የቡና ስኒ", rom: "Ye Buna Sini", en: "Coffee cup" },
  jebena: { am: "ጀበና", rom: "Jebena", en: "Coffee pot" },
  jebna: { am: "ጀበና", rom: "Jebena", en: "Coffee pot" },
  teabag: { am: "የሻይ ከረጢት", rom: "Ye Shay Keretit", en: "Tea bag" },
  addisteabag: { am: "አዲስ የሻይ ከረጢት", rom: "Addis Ye Shay Keretit", en: "Addis tea bag" },
  adistea: { am: "አዲስ ሻይ", rom: "Addis Shay", en: "Addis tea" },
  greentea: { am: "አረንጓዴ ሻይ", rom: "Arengwade Shay", en: "Green tea" },
  gerentea: { am: "አረንጓዴ ሻይ", rom: "Arengwade Shay", en: "Green tea" },
  greenteabag: { am: "አረንጓዴ የሻይ ከረጢት", rom: "Arengwade Ye Shay Keretit", en: "Green tea bag" },
  mentteabag: { am: "የሚንት የሻይ ከረጢት", rom: "Ye Mint Ye Shay Keretit", en: "Mint tea bag" },
  anbesatea: { am: "አንበሳ ሻይ", rom: "Anbesa Shay", en: "Anbesa tea" },
  wushwush: { am: "ውሽውሽ", rom: "Wushwush", en: "Wushwush tea" },
  wushiwushitea: { am: "ውሽውሽ ሻይ", rom: "Wushwush Shay", en: "Wushwush tea" },
  yeshaye: { am: "የሻይ", rom: "Ye Shay", en: "Tea item" },
  shayebercheko: { am: "የሻይ ብርጭቆ", rom: "Ye Shay Birchiko", en: "Tea glass" },
  especialshaybrchko: { am: "ልዩ የሻይ ብርጭቆ", rom: "Liyu Ye Shay Birchiko", en: "Special tea glass" },
  water: { am: "ውሃ", rom: "Wuha", en: "Water" },
  bigwater: { am: "ትልቅ ውሃ", rom: "Tilq Wuha", en: "Large water" },
  midwater: { am: "መካከለኛ ውሃ", rom: "Mekakelena Wuha", en: "Medium water" },
  midumwater: { am: "መካከለኛ ውሃ", rom: "Mekakelena Wuha", en: "Medium water" },
  smallwater: { am: "ትንሽ ውሃ", rom: "Tinish Wuha", en: "Small water" },
  ambowuha: { am: "አምቦ ውሃ", rom: "Ambo Wuha", en: "Ambo mineral water" },
  ambo: { am: "አምቦ", rom: "Ambo", en: "Ambo water" },
  ambowater: { am: "አምቦ ውሃ", rom: "Ambo Wuha", en: "Ambo mineral water" },
  amebo: { am: "አምቦ", rom: "Ambo", en: "Ambo water" },
  kybotiwuha: { am: "የቦቲ ውሃ", rom: "Ye Boti Wuha", en: "Bottle water" },
  yebotiwuha: { am: "የቦቲ ውሃ", rom: "Ye Boti Wuha", en: "Bottle water" },
  yewuhabercheko: { am: "የውሃ ብርጭቆ", rom: "Ye Wuha Birchiko", en: "Water glass" },
  beer: { am: "ቢራ", rom: "Bira", en: "Beer" },
  normalbeer: { am: "መደበኛ ቢራ", rom: "Medebeña Bira", en: "Normal beer" },
  specailbeer: { am: "ልዩ ቢራ", rom: "Liyu Bira", en: "Special beer" },
  bedelasepashalebeer: { am: "ቤዴላ ልዩ ቢራ", rom: "Bedela Liyu Bira", en: "Bedele special beer" },
  dashenbeer: { am: "ዳሽን ቢራ", rom: "Dashen Bira", en: "Dashen beer" },
  habeshabeer: { am: "ሐበሻ ቢራ", rom: "Habesha Bira", en: "Habesha beer" },
  harerebeer: { am: "ሐረር ቢራ", rom: "Harar Bira", en: "Harar beer" },
  goregesbeer: { am: "ጎርጎራ ቢራ", rom: "Gorgora Bira", en: "Gorgora beer" },
  sofibbeer: { am: "ሶፊ ቢራ", rom: "Sofi Bira", en: "Sofi beer" },
  sofibeer: { am: "ሶፊ ቢራ", rom: "Sofi Bira", en: "Sofi beer" },
  hinkenebeer: { am: "ሄኔከን ቢራ", rom: "Heineken Bira", en: "Heineken beer" },
  heineken: { am: "ሄኔከን", rom: "Heineken", en: "Heineken" },
  hinken: { am: "ሄኔከን", rom: "Heineken", en: "Heineken" },
  berahinken: { am: "ቢራ ሄኔከን", rom: "Bira Heineken", en: "Heineken beer" },
  cocacola: { am: "ኮካ ኮላ", rom: "Coca Cola", en: "Coca-Cola" },
  softdrinkcoca: { am: "ኮካ ኮላ", rom: "Coca Cola", en: "Coca-Cola soft drink" },
  pepsi: { am: "ፔፕሲ", rom: "Pepsi", en: "Pepsi" },
  softdirnkpepis: { am: "ፔፕሲ", rom: "Pepsi", en: "Pepsi soft drink" },
  mirinda: { am: "ሚሪንዳ", rom: "Mirinda", en: "Mirinda" },
  softdrinkmirnda: { am: "ሚሪንዳ", rom: "Mirinda", en: "Mirinda soft drink" },
  softdrink: { am: "ለስላሳ መጠጥ", rom: "Leslasa Metet", en: "Soft drink" },
  softdrike: { am: "ለስላሳ መጠጥ", rom: "Leslasa Metet", en: "Soft drink" },
  vento: { am: "ቬንቶ", rom: "Vento", en: "Vento drink" },
  vinto: { am: "ቪንቶ", rom: "Vinto", en: "Vinto drink" },
  sofymalita: { am: "ሶፊ ማልታ", rom: "Sofi Malta", en: "Sofi Malta" },
  sofymalta: { am: "ሶፊ ማልታ", rom: "Sofi Malta", en: "Sofi Malta" },
  jam: { am: "ጃም", rom: "Jam", en: "Jam" },
  ketchup: { am: "ኬጨፕ", rom: "Ketchup", en: "Ketchup" },
  katchup: { am: "ኬጨፕ", rom: "Ketchup", en: "Ketchup" },
  cuchap: { am: "ኬጨፕ", rom: "Ketchup", en: "Ketchup" },
  catchup: { am: "ኬጨፕ", rom: "Ketchup", en: "Ketchup" },
  mayoniz: { am: "ማዮኔዝ", rom: "Mayonnaise", en: "Mayonnaise" },
  soysouce: { am: "ሶያ ሶስ", rom: "Soya Sos", en: "Soy sauce" },
  darksoya: { am: "ጨለማ ሶያ", rom: "Chelema Soya", en: "Dark soy sauce" },
  darksoysos: { am: "ጨለማ ሶያ ሶስ", rom: "Chelema Soya Sos", en: "Dark soy sauce" },
  lightsoya: { am: "ቀላል ሶያ", rom: "Kelal Soya", en: "Light soy sauce" },
  lighetsoysos: { am: "ቀላል ሶያ ሶስ", rom: "Kelal Soya Sos", en: "Light soy sauce" },
  lightanddarksoya: { am: "ቀላልና ጨለማ ሶያ", rom: "Kelal Na Chelema Soya", en: "Light and dark soy" },
  sosydark: { am: "ጨለማ ሶስ", rom: "Chelema Sos", en: "Dark sauce" },
  sosylight: { am: "ቀላል ሶስ", rom: "Kelal Sos", en: "Light sauce" },
  soysoslighte: { am: "ቀላል ሶያ ሶስ", rom: "Kelal Soya Sos", en: "Light soy sauce" },
  blackolive: { am: "ጥቁር ኦሊቭ", rom: "Tikur Olive", en: "Black olive" },
  blackcoopolivebig: { am: "ጥቁር ኦሊቭ", rom: "Tikur Olive", en: "Black olive (large)" },
  oliva: { am: "ኦሊቫ", rom: "Oliva", en: "Olive" },
  olivabig: { am: "ኦሊቫ", rom: "Oliva", en: "Olive (large)" },
  olivalarge: { am: "ኦሊቫ", rom: "Oliva", en: "Olive (large)" },
  olivasmall: { am: "ኦሊቫ", rom: "Oliva", en: "Olive (small)" },
  knor: { am: "ኖር", rom: "Knorr", en: "Knorr seasoning" },
  knore: { am: "ኖር", rom: "Knorr", en: "Knorr seasoning" },
  knorr: { am: "ኖር", rom: "Knorr", en: "Knorr seasoning" },
  kennor: { am: "ኖር", rom: "Knorr", en: "Knorr seasoning" },
  magimix: { am: "ማጊ ሚክስ", rom: "Maggi Mix", en: "Maggi mix" },

  // Cleaning / laundry (careful: shbo ≠ shiro)
  shbo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  shebo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  shibo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  ekamatebeyashebo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  ekamatebayashebo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  ekamatebiyashbo: { am: "ሽቦ", rom: "Shbo", en: "Cleaning detergent" },
  omo: { am: "ኦሞ", rom: "Omo", en: "Omo detergent" },
  crownomo: { am: "ክራውን ኦሞ", rom: "Crown Omo", en: "Crown Omo detergent" },
  sunlight: { am: "ሳንላይት", rom: "Sunlight", en: "Sunlight soap" },
  sunlihgtomo: { am: "ሳንላይት ኦሞ", rom: "Sunlight Omo", en: "Sunlight / Omo" },
  ajax: { am: "አጃክስ", rom: "Ajax", en: "Ajax cleaner" },
  ajaks: { am: "አጃክስ", rom: "Ajax", en: "Ajax cleaner" },
  ajaxbig: { am: "አጃክስ", rom: "Ajax", en: "Ajax cleaner (large)" },
  bleach: { am: "ብሊች", rom: "Bleach", en: "Bleach" },
  berekina: { am: "በረኪና", rom: "Berekina", en: "Chlorine bleach" },
  vim: { am: "ቪም", rom: "Vim", en: "Vim cleaner" },
  vime: { am: "ቪም", rom: "Vim", en: "Vim cleaner" },
  dettol: { am: "ዴቶል", rom: "Dettol", en: "Dettol disinfectant" },
  detol: { am: "ዴቶል", rom: "Dettol", en: "Dettol disinfectant" },
  dishwashing: { am: "የእቃ ማጠቢያ", rom: "Ye Eka Matebiya", en: "Dish washing" },
  dishwash: { am: "የእቃ ማጠቢያ", rom: "Ye Eka Matebiya", en: "Dish wash" },
  largodishwash: { am: "ላርጎ የእቃ ማጠቢያ", rom: "Largo Ye Eka Matebiya", en: "Largo dish wash" },
  largo: { am: "ላርጎ", rom: "Largo", en: "Largo cleaner" },
  largoliquidsoap: { am: "ላርጎ ፈሳሽ ሳሙና", rom: "Largo Fesash Samuna", en: "Largo liquid soap" },
  liquidsoap: { am: "ፈሳሽ ሳሙና", rom: "Fesash Samuna", en: "Liquid soap" },
  soap: { am: "ሳሙና", rom: "Samuna", en: "Soap" },
  bathsoap: { am: "የመታጠቢያ ሳሙና", rom: "Ye Metatebiya Samuna", en: "Bath soap" },
  handwash: { am: "የእጅ ማጠቢያ", rom: "Ye Ej Matebiya", en: "Hand wash" },
  softner: { am: "ሶፍትነር", rom: "Softener", en: "Fabric softener" },
  toiletcleaner: { am: "የሽንት ቤት ማጽጃ", rom: "Ye Shint Bet Metsija", en: "Toilet cleaner" },
  windowcleaner: { am: "የመስኮት ማጽጃ", rom: "Ye Meskot Metsija", en: "Window cleaner" },
  sanitayzer: { am: "ሳኒታይዘር", rom: "Sanitizer", en: "Sanitizer" },
  alcohol: { am: "አልኮል", rom: "Alcohol", en: "Alcohol" },
  alcholfree: { am: "ከአልኮል ነፃ", rom: "Ke Alcohol Netsa", en: "Alcohol free" },

  // Paper / packaging / kitchenware (selected)
  napkin: { am: "ናፕኪን", rom: "Napkin", en: "Napkin" },
  gebetasoftnapkin: { am: "ገበታ ሶፍት / ናፕኪን", rom: "Gebeta Soft / Napkin", en: "Soft napkin" },
  straw: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  stro: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  extrasstraw: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  extrastraw: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  estrow: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  estro: { am: "ስትሮ", rom: "Stro", en: "Drinking straw" },
  // Estracho family is NOT drinking straw — keep name as itself
  estracho: { am: "ኤስትራቾ", rom: "Estracho", en: "Estracho" },
  esteracho: { am: "ኤስትራቾ", rom: "Estracho", en: "Estracho" },
  esetercho: { am: "ኤስትራቾ", rom: "Estracho", en: "Estracho" },
  eseteracho: { am: "ኤስትራቾ", rom: "Estracho", en: "Estracho" },
  touthpick: { am: "የጥርስ መንጫ", rom: "Ye Tirs Mencha", en: "Toothpick" },
  gloves: { am: "ጓንት", rom: "Gwant", en: "Gloves" },
  glove: { am: "ጓንት", rom: "Gwant", en: "Glove" },
  glovee: { am: "ጓንት", rom: "Gwant", en: "Glove" },
  disposablegloves: { am: "አንድ ጊዜ ጓንት", rom: "And Gize Gwant", en: "Disposable gloves" },
  disosableglove: { am: "አንድ ጊዜ ጓንት", rom: "And Gize Gwant", en: "Disposable glove" },
  disglove: { am: "ጓንት", rom: "Gwant", en: "Disposable glove" },
  match: { am: "እሳት ቀጣይ", rom: "Isat Qetay", en: "Match" },
  kbrit: { am: "ክብሪት", rom: "Kibrit", en: "Matchbox" },
  sponge: { am: "ስፖንጅ", rom: "Sponj", en: "Sponge" },
  spong: { am: "ስፖንጅ", rom: "Sponj", en: "Sponge" },
  sponj: { am: "ስፖንጅ", rom: "Sponj", en: "Sponge" },
  spnje: { am: "ስፖንጅ", rom: "Sponj", en: "Sponge" },
  esponje: { am: "ስፖንጅ", rom: "Sponj", en: "Sponge" },
  brush: { am: "ብሩሽ", rom: "Brush", en: "Brush" },
  mask: { am: "ማስክ", rom: "Mask", en: "Mask" },
  cotton: { am: "ጥጥ", rom: "Tit", en: "Cotton" },

  // Hardware / office (English-leaning; Amharic loan or common term when known)
  toner: { am: "ቶነር", rom: "Toner", en: "Printer toner" },
  pump: { am: "ፓምፕ", rom: "Pump", en: "Pump" },
  lamp: { am: "ላምፕ", rom: "Lamp", en: "Lamp" },
  lump: { am: "ላምፕ", rom: "Lamp", en: "Lamp" },
  battery: { am: "ባትሪ", rom: "Battery", en: "Battery" },
  nail: { am: "ምስማር", rom: "Mismar", en: "Nail" },
  cement: { am: "ሲሚንቶ", rom: "Siminto", en: "Cement" },
  semento: { am: "ሲሚንቶ", rom: "Siminto", en: "Cement" },
  sminto: { am: "ሲሚንቶ", rom: "Siminto", en: "Cement" },
  pen: { am: "ብዕር", rom: "Bir", en: "Pen" },
  penbic: { am: "ቢክ ብዕር", rom: "Bic Bir", en: "Bic pen" },
  notebook: { am: "ማስታወሻ ደብተር", rom: "Mastawesha Debter", en: "Notebook" },
  debter: { am: "ደብተር", rom: "Debter", en: "Exercise book" },
  stappler: { am: "ስቴፕለር", rom: "Stapler", en: "Stapler" },
  stapler: { am: "ስቴፕለር", rom: "Stapler", en: "Stapler" },
  ruler: { am: "መለኪያ", rom: "Melekia", en: "Ruler" },
  copypaper: { am: "የኮፒ ወረቀት", rom: "Ye Copy Wereket", en: "Copy paper" },
  copywerket: { am: "የኮፒ ወረቀት", rom: "Ye Copy Wereket", en: "Copy paper" },
  a4paper: { am: "ኤ4 ወረቀት", rom: "A4 Wereket", en: "A4 paper" },
  bigprinterpaper: { am: "ትልቅ የፕሪንተር ወረቀት", rom: "Tilq Ye Printer Wereket", en: "Large printer paper" },
  smallprinterpaper: { am: "ትንሽ የፕሪንተር ወረቀት", rom: "Tinish Ye Printer Wereket", en: "Small printer paper" },
  bakingpaper: { am: "የቤኪንግ ወረቀት", rom: "Ye Baking Wereket", en: "Baking paper" },
  backigpaper: { am: "የቤኪንግ ወረቀት", rom: "Ye Baking Wereket", en: "Baking paper" },
  aluminiumfoil: { am: "አሉሚኒየም ፎይል", rom: "Aluminium Foil", en: "Aluminium foil" },
  almuniumfoil: { am: "አሉሚኒየም ፎይል", rom: "Aluminium Foil", en: "Aluminium foil" },
  plasticfoil: { am: "ፕላስቲክ ፎይል", rom: "Plastic Foil", en: "Plastic foil" },
  wifi: { am: "ዋይፋይ", rom: "Wifi", en: "Wi-Fi" },
  mouse: { am: "ማውስ", rom: "Mouse", en: "Computer mouse" },
  mause: { am: "ማውስ", rom: "Mouse", en: "Computer mouse" },
  flashdisk: { am: "ፍላሽ ዲስክ", rom: "Flash Disk", en: "USB flash drive" },

  // Fabric / traditional
  abojeda: { am: "አቡጀዲ", rom: "Abujedi", en: "Cotton cloth" },
  abujdi: { am: "አቡጀዲ", rom: "Abujedi", en: "Cotton cloth" },
  abujedicherk: { am: "አቡጀዲ ጨርቅ", rom: "Abujedi Cherk", en: "Abujedi fabric" },
  bahlawilebs: { am: "ባህላዊ ልብስ", rom: "Bahilawi Lebs", en: "Traditional clothes" },
  shama: { am: "ሻማ", rom: "Shama", en: "Candle / shawl context" },
  shemiz: { am: "ሸሚዝ", rom: "Shemiz", en: "Shirt" },
  tshirt: { am: "ቲሸርት", rom: "T-shirt", en: "T-shirt" },
  kemise: { am: "ቀሚስ", rom: "Qemis", en: "Dress / kemis" },

  // Misc kitchen Amharic phrases often seen
  mitad: { am: "ምጣድ", rom: "Mitad", en: "Injera griddle" },
  metade: { am: "ምጣድ", rom: "Mitad", en: "Injera griddle" },
  yemetadeberaker: { am: "የምጣድ በራከር", rom: "Ye Mitad Beraker", en: "Mitad burner" },
  beraker: { am: "በራከር", rom: "Beraker", en: "Burner" },
  enjeralasetic: { am: "የእንጀራ ፕላስቲክ", rom: "Ye Injera Plastic", en: "Injera plastic wrap" },
  injeraplastic: { am: "የእንጀራ ፕላስቲክ", rom: "Ye Injera Plastic", en: "Injera plastic wrap" },
  yeenjeralastek: { am: "የእንጀራ ፕላስቲክ", rom: "Ye Injera Plastic", en: "Injera plastic wrap" },
  mesabeya: { am: "መሳቢያ", rom: "Mesabiya", en: "Mesabiya" },
  mesabiya: { am: "መሳቢያ", rom: "Mesabiya", en: "Mesabiya" },
  sefade: { am: "ሰፋድ", rom: "Sefad", en: "Sefad" },
  sefede: { am: "ሰፋድ", rom: "Sefad", en: "Sefad" },
  sefedemesabeya: { am: "ሰፋድ / መሳቢያ", rom: "Sefad / Mesabiya", en: "Sefad / Mesabiya" },
  koba: { am: "ቆባ", rom: "Koba", en: "Bowl / basin" },
  kobayeburet: { am: "የቡሬት ቆባ", rom: "Ye Buret Koba", en: "Kitchen bowl" },
  kobayekichen: { am: "የኩሽና ቆባ", rom: "Ye Kushina Koba", en: "Kitchen bowl" },
  elebo: { am: "እልቦ", rom: "Elbo", en: "Elbo" },
  feamalelebo: { am: "ሴት እልቦ", rom: "Set Elbo", en: "Female Elbo" },
  femaleelebo: { am: "ሴት እልቦ", rom: "Set Elbo", en: "Female Elbo" },
  mashela: { am: "ማሽላ", rom: "Mashela", en: "Sorghum" },
  aceto: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  acheto: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  achto: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  vinegar: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  acetovinegar: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  achetovinegar: { am: "አቸቶ", rom: "Acheto", en: "Vinegar" },
  akezha: { am: "አከዣ", rom: "Akezha", en: "Akezha" },
  akeja: { am: "አከዣ", rom: "Akezha", en: "Akezha" },
  belewa: { am: "በለዋ", rom: "Belewa", en: "Belewa" },
  belawayeatekelte: { am: "በለዋ የአትክልት", rom: "Belewa Ye Atkilt", en: "Belewa ye atkilt" },
  // Esteplar shbo ≠ eka matebiya shbo
  esetapraleshebo: { am: "ኤስቴፕላር ሽቦ", rom: "Esteplar Shbo", en: "Esteplar shbo" },
  setapelareshebo: { am: "ኤስቴፕላር ሽቦ", rom: "Esteplar Shbo", en: "Esteplar shbo" },
  esteplarshebo: { am: "ኤስቴፕላር ሽቦ", rom: "Esteplar Shbo", en: "Esteplar shbo" },
  esteplarshbo: { am: "ኤስቴፕላር ሽቦ", rom: "Esteplar Shbo", en: "Esteplar shbo" },
  blacklabel: { am: "ብላክ ሌብል", rom: "Black Label", en: "Black Label" },
  castle: { am: "ካስል", rom: "Castle", en: "Castle beer" },
  awash: { am: "አዋሽ", rom: "Awash", en: "Awash" },
  awsh: { am: "አዋሽ", rom: "Awash", en: "Awash" },
  baro: { am: "ባሮ", rom: "Baro", en: "Baro" },
  bera: { am: "ቢራ", rom: "Bira", en: "Beer" },
  beraarda: { am: "ቢራ አርዳ", rom: "Bira Arda", en: "Draft beer" },
  ardabera: { am: "አርዳ ቢራ", rom: "Arda Bira", en: "Draft beer" },
  berakehulum: { am: "ቢራ ከሁሉም", rom: "Bira Ke Hulum", en: "Beer assortment" },
  negus: { am: "ንጉስ", rom: "Negus", en: "Negus" },
  nigus: { am: "ንጉስ", rom: "Negus", en: "Negus" },
  negusebera: { am: "ንጉስ ቢራ", rom: "Negus Bira", en: "Negus beer" },
  senqe: { am: "ሰንቅ", rom: "Senq", en: "Senqe snack" },
  sokat: { am: "ሶካት", rom: "Sokat", en: "Sokat" },
  sokate: { am: "ሶካት", rom: "Sokat", en: "Sokat" },
  yesoketchaef: { am: "የሶካት ጫፍ", rom: "Ye Sokat Chaf", en: "Sokat tip" },
  silken: { am: "ሲልከን", rom: "Silken", en: "Silken" },
  whitekondeba: { am: "ነጭ ቆንድባ", rom: "Nech Kondiba", en: "White kondiba" },
  derekazmerino: { am: "ደረቅ አዝመሪኖ", rom: "Derek Azmerino", en: "Dry rosemary" },
  azmerino: { am: "አዝመሪኖ", rom: "Azmerino", en: "Rosemary" },
  azemrino: { am: "አዝመሪኖ", rom: "Azmerino", en: "Rosemary" },
  dereskoshasha: { am: "ደረቅ ቆሻሻ", rom: "Derek Qoshasha", en: "Dry waste / scrap" },
  deresegn: { am: "ደረሰኝ", rom: "Deresegn", en: "Receipt" },
  dersegh: { am: "ደረሰኝ", rom: "Deresegn", en: "Receipt" },
  yedersegnwerket: { am: "የደረሰኝ ወረቀት", rom: "Ye Deresegn Wereket", en: "Receipt paper" },
  yednchmelacha: { am: "የድንች መላጫ", rom: "Ye Dinich Melacha", en: "Potato peeler" },
  yefendeshamashen: { am: "የፈንዲሻ ማሽን", rom: "Ye Fendisha Mashen", en: "Popcorn machine" },
  yemakyatobrchko: { am: "የማቅያቶ ብርጭቆ", rom: "Ye Makiyato Birchiko", en: "Macchiato glass" },
  yemachiyatobrchko: { am: "የማቅያቶ ብርጭቆ", rom: "Ye Makiyato Birchiko", en: "Macchiato glass" },
  yemagedoenchet: { am: "የማገዶ እንጨት", rom: "Ye Magedo Enchet", en: "Firewood" },
  yeweyraenchet: { am: "የወይራ እንጨት", rom: "Ye Weyra Enchet", en: "Olive wood" },
  yelebeselargo: { am: "የልብስ ላርጎ", rom: "Ye Lebs Largo", en: "Laundry Largo" },
  yemeretlargo: { am: "የመሬት ላርጎ", rom: "Ye Meret Largo", en: "Floor Largo" },
  yemeretwelel: { am: "የመሬት ወለል", rom: "Ye Meret Welel", en: "Floor surface cleaner" },
  lawundarysoapyemeretlargo: {
    am: "የልብስ ሳሙና / የመሬት ላርጎ",
    rom: "Ye Lebs Samuna / Ye Meret Largo",
    en: "Laundry soap / floor Largo",
  },
  lawunderlargo: { am: "ላውንደር ላርጎ", rom: "Laundry Largo", en: "Laundry Largo" },
  liquidlargolawunderlargo: {
    am: "ፈሳሽ ላርጎ / ላውንደር ላርጎ",
    rom: "Fesash Largo / Laundry Largo",
    en: "Liquid Largo / laundry Largo",
  },
  nifaskokeb: { am: "ንፋስ ኮከብ", rom: "Nifas Kokeb", en: "Nifas Kokeb oil" },
  nifaskokebgalon: { am: "ንፋስ ኮከብ ጋሎን", rom: "Nifas Kokeb Galon", en: "Nifas Kokeb gallon" },
  shenolega: { am: "ሸኖ ለጋ", rom: "Sheno Lega", en: "Sheno Lega oil" },
  artefshalsar: { am: "አርቴፊሻል ሳር", rom: "Artificial Sar", en: "Artificial grass" },
  aoshkiller: { am: "የትንኝ መግደያ", rom: "Ye Tinin Megdeya", en: "Mosquito killer" },
  gazeta: { am: "ጋዜጣ", rom: "Gazeta", en: "Newspaper" },
  agenda: { am: "አጀንዳ", rom: "Agenda", en: "Agenda notebook" },
  carbon: { am: "ካርቦን", rom: "Carbon", en: "Carbon paper" },
  kelem: { am: "ቀለም", rom: "Qelem", en: "Ink / paint" },
  copykeleme: { am: "የኮፒ ቀለም", rom: "Ye Copy Qelem", en: "Copy ink" },
  yeconpterkelem: { am: "የኮምፒውተር ቀለም", rom: "Ye Computer Qelem", en: "Computer ink" },
  comepeterkelem: { am: "የኮምፒውተር ቀለም", rom: "Ye Computer Qelem", en: "Computer ink" },
  kulfe: { am: "ቁልፍ", rom: "Qulf", en: "Key / lock" },
  tewerwarikulfe: { am: "ተዘዋዋሪ ቁልፍ", rom: "Tezewawari Qulf", en: "Master key" },
  slinderkulfe: { am: "የሲሊንደር ቁልፍ", rom: "Ye Cylinder Qulf", en: "Cylinder lock key" },
  yebefakulef: { am: "የበር ቁልፍ", rom: "Ye Ber Qulf", en: "Door key" },
  yekulefmeletfeya: { am: "የቁልፍ መክፈቻ", rom: "Ye Qulf Mekfeticha", en: "Key opener" },
  doorlock: { am: "የበር መቆለፊያ", rom: "Ye Ber Meqolefiya", en: "Door lock" },
  doornbelt: { am: "የበር ቀበቶ", rom: "Ye Ber Qebeto", en: "Door belt" },
  doorbelt: { am: "የበር ቀበቶ", rom: "Ye Ber Qebeto", en: "Door belt" },

  // High-hit previously unmapped inventory (careful meanings)
  soft: { am: "ሶፍት", rom: "Soft", en: "Soft tissue paper" },
  rollsoft: { am: "ሶፍት", rom: "Soft", en: "Soft tissue paper" },
  kichenrollsoft: { am: "ሶፍት", rom: "Soft", en: "Soft tissue paper" },
  toiletsoft: { am: "የሽንት ቤት ሶፍት", rom: "Ye Shint Bet Soft", en: "Toilet soft paper" },
  poreshenpasetale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  poreshenpesetale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  poreshenpestal: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  poresenpesetale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  poreshenpesatale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  poreshenpestale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  porshenpesatale: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  portionplastic: { am: "ፖርሽን ፕላስቲክ", rom: "Portion Plastic", en: "Portion plastic bag" },
  portionfestal: { am: "ፖርሽን ፌስታል", rom: "Portion Festal", en: "Portion plastic bag" },
  portionpestal: { am: "ፖርሽን ፌስታል", rom: "Portion Festal", en: "Portion plastic bag" },
  tekaweypesetale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  tekaweypasetale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  tekaweyepesetale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  takawypestal: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  tekaweypestale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  tekawypastale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  tekeaweypesetale: { am: "ቴካዌይ ፕላስቲክ", rom: "Tekawey Plastic", en: "Takeaway plastic bag" },
  zekuni: { am: "ዝኩኒ", rom: "Zikuni", en: "Zucchini" },
  zukuni: { am: "ዝኩኒ", rom: "Zikuni", en: "Zucchini" },
  kesel: { am: "ከሰል", rom: "Kesel", en: "Charcoal" },
  shanticream: { am: "ሻንቲ ክሬም", rom: "Shanti Cream", en: "Shanti whipping cream" },
  coba: { am: "ቆባ", rom: "Koba", en: "Basin / bowl" },
  denebelale: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  dnblal: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  denbelale: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  denblale: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  denebelle: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  dinblal: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  dnblale: { am: "ድንብላል", rom: "Dinbilal", en: "Coriander / cilantro" },
  foodcolour: { am: "የምግብ ቀለም", rom: "Ye Migb Qelem", en: "Food colour" },
  foodcolor: { am: "የምግብ ቀለም", rom: "Ye Migb Qelem", en: "Food colour" },
  foodcolouryellow: { am: "ቢጫ የምግብ ቀለም", rom: "Bicha Ye Migb Qelem", en: "Yellow food colour" },
  foodcolourred: { am: "ቀይ የምግብ ቀለም", rom: "Key Ye Migb Qelem", en: "Red food colour" },
  airfrash: { am: "የአየር ማሽተኛ", rom: "Ye Ayer Mashiteña", en: "Air freshener" },
  airfresh: { am: "የአየር ማሽተኛ", rom: "Ye Ayer Mashiteña", en: "Air freshener" },
  nafeta: { am: "ናፍጣ", rom: "Nafta", en: "Diesel / naphtha" },
  filebox: { am: "የፋይል ሳጥን", rom: "Ye File Satin", en: "File box" },
  boxfile: { am: "የፋይል ሳጥን", rom: "Ye File Satin", en: "File box" },
  eskerbito: { am: "እስኬርቢቶ", rom: "Eskerbito", en: "Scouring pad" },
  bikeskerberto: { am: "እስኬርቢቶ", rom: "Eskerbito", en: "Scouring pad" },
  lexieskerbito: { am: "ሌክሲ እስኬርቢቶ", rom: "Lexi Eskerbito", en: "Lexi scouring pad" },
  lexieskerberto: { am: "ሌክሲ እስኬርቢቶ", rom: "Lexi Eskerbito", en: "Lexi scouring pad" },
  soyasouce: { am: "ሶያ ሶስ", rom: "Soya Sos", en: "Soy sauce" },
  bere: { am: "በር", rom: "Ber", en: "Door" },
  keberte: { am: "ከበረት", rom: "Keberet", en: "Keberet" },
  keberite: { am: "ከበረት", rom: "Keberet", en: "Keberet" },
  keberet: { am: "ከበረት", rom: "Keberet", en: "Keberet" },
  meberte: { am: "ከበረት", rom: "Keberet", en: "Keberet" },
  telkufestal: { am: "ትልቁ ፌስታል", rom: "Tilku Festal", en: "Large plastic bag" },
  tenshufestal: { am: "ትንሹ ፌስታል", rom: "Tinshu Festal", en: "Small plastic bag" },
  slindergas: { am: "ሲሊንደር ጋዝ", rom: "Silinder Gaz", en: "Gas cylinder" },
  silderlpgas: { am: "ሲሊንደር ጋዝ", rom: "Silinder Gaz", en: "LP gas cylinder" },
  estikini: { am: "እስቲኪኒ", rom: "Estikini", en: "Estikini" },
  estekini: { am: "እስቲኪኒ", rom: "Estikini", en: "Estikini" },
  istekini: { am: "እስቲኪኒ", rom: "Estikini", en: "Estikini" },
  istkini: { am: "እስቲኪኒ", rom: "Estikini", en: "Estikini" },
  capetanorder: { am: "ካፒቴን ኦርደር", rom: "Captain Order", en: "Captain order pad" },
  capitainorder: { am: "ካፒቴን ኦርደር", rom: "Captain Order", en: "Captain order pad" },
  captanorder: { am: "ካፒቴን ኦርደር", rom: "Captain Order", en: "Captain order pad" },
  meweleweya: { am: "መወለወያ", rom: "Meweleweya", en: "Whisk / beater" },
  mewolwoya: { am: "መወለወያ", rom: "Meweleweya", en: "Whisk / beater" },
  mafesha: { am: "መፍቻ", rom: "Mefcha", en: "Opener" },
  plaster: { am: "ፕላስተር", rom: "Plaster", en: "Plaster / bandage" },
  nastro: { am: "ናስትሮ", rom: "Nastro", en: "Adhesive tape" },
  nastero: { am: "ናስትሮ", rom: "Nastro", en: "Adhesive tape" },
  ketema: { am: "ከተማ", rom: "Ketema", en: "Ketema" },
  pizzabox: { am: "የፒዛ ሳጥን", rom: "Ye Pizza Satin", en: "Pizza box" },
  takeawaybox: { am: "የቴካዌይ ሳጥን", rom: "Ye Tekawey Satin", en: "Takeaway box" },
  teakaweybox: { am: "የቴካዌይ ሳጥን", rom: "Ye Tekawey Satin", en: "Takeaway box" },
  teakawey: { am: "ቴካዌይ", rom: "Tekawey", en: "Takeaway" },
  cakebox: { am: "የኬክ ሳጥን", rom: "Ye Cake Satin", en: "Cake box" },
  caketakawybox: { am: "የኬክ ቴካዌይ ሳጥን", rom: "Ye Cake Tekawey Satin", en: "Cake takeaway box" },
  checolatesyrup: { am: "የቸኮሌት ሽሮፕ", rom: "Ye Chocolate Syrop", en: "Chocolate syrup" },
  checoletsrape: { am: "የቸኮሌት ሽሮፕ", rom: "Ye Chocolate Syrop", en: "Chocolate syrup" },
  chocolateserap: { am: "የቸኮሌት ሽሮፕ", rom: "Ye Chocolate Syrop", en: "Chocolate syrup" },
  checkoletcerap: { am: "የቸኮሌት ሽሮፕ", rom: "Ye Chocolate Syrop", en: "Chocolate syrup" },
  strawberysyrap: { am: "የስትሮቤሪ ሽሮፕ", rom: "Ye Strawberry Syrop", en: "Strawberry syrup" },
  stroverycerap: { am: "የስትሮቤሪ ሽሮፕ", rom: "Ye Strawberry Syrop", en: "Strawberry syrup" },
  pancakesyrap: { am: "የፓንኬክ ሽሮፕ", rom: "Ye Pancake Syrop", en: "Pancake syrup" },
  foseter: { am: "ፎስተር", rom: "Foster", en: "Foster beer" },
  foster: { am: "ፎስተር", rom: "Foster", en: "Foster beer" },
  supergato: { am: "ሱፐር ጋቶ", rom: "Super Gato", en: "Super Gato pastry" },
  amepole: { am: "አምፖል", rom: "Ampole", en: "Light bulb" },
  ampole: { am: "አምፖል", rom: "Ampole", en: "Light bulb" },
  anepole: { am: "አምፖል", rom: "Ampole", en: "Light bulb" },
  anpole: { am: "አምፖል", rom: "Ampole", en: "Light bulb" },
  mashenpaper: { am: "የማሽን ወረቀት", rom: "Ye Mashen Wereket", en: "Machine paper" },
  masheinpaper: { am: "የማሽን ወረቀት", rom: "Ye Mashen Wereket", en: "Machine paper" },
  anglevalue: { am: "አንግል ቫልቭ", rom: "Angle Valve", en: "Angle valve" },
  ashewa: { am: "አሸዋ", rom: "Ashewa", en: "Sand" },
  mesherumbig: { am: "እንጉዳይ", rom: "Enguday", en: "Mushroom (large)" },
  metregya: { am: "መጥረጊያ", rom: "Metregiya", en: "Broom" },
  metergeya: { am: "መጥረጊያ", rom: "Metregiya", en: "Broom" },
  metiregiya: { am: "መጥረጊያ", rom: "Metregiya", en: "Broom" },
  shutup: { am: "ሹት ኦፍ", rom: "Shut Off", en: "Shut-off valve" },
  kamilate: { am: "ካሚላ", rom: "Kamila", en: "Chamomile" },
  kamilat: { am: "ካሚላ", rom: "Kamila", en: "Chamomile" },
  kamila: { am: "ካሚላ", rom: "Kamila", en: "Chamomile" },
  kamilateweyen: { am: "ካሚላ ወይን", rom: "Kamila Weyn", en: "Chamomile wine / drink" },
  bigplastic: { am: "ትልቅ ፕላስቲክ", rom: "Tilq Plastic", en: "Large plastic bag" },
  h2optinner: { am: "ኤች2ኦፒ ቲነር", rom: "H2OP Thinner", en: "H2OP paint thinner" },
  h20ptinner: { am: "ኤች2ኦፒ ቲነር", rom: "H2OP Thinner", en: "H2OP paint thinner" },
  cashridisterroll: { am: "የካሽ ሬጂስተር ሮል", rom: "Ye Cash Register Roll", en: "Cash register roll" },
  cashrigisterroll: { am: "የካሽ ሬጂስተር ሮል", rom: "Ye Cash Register Roll", en: "Cash register roll" },
  cashrigisterpaper: { am: "የካሽ ሬጂስተር ወረቀት", rom: "Ye Cash Register Wereket", en: "Cash register paper" },
  receiptsncr: { am: "ኤንሲአር ደረሰኝ", rom: "NCR Receipt", en: "NCR receipt paper" },
  resistance: { am: "ሬዚስተንስ", rom: "Resistance", en: "Electrical resistor" },
  risistance: { am: "ሬዚስተንስ", rom: "Resistance", en: "Electrical resistor" },
  resister: { am: "ሬዚስተር", rom: "Resistor", en: "Electrical resistor" },
  berkeni: { am: "በረኪና", rom: "Berekina", en: "Chlorine bleach" },
  frije: { am: "ፍሪጅ", rom: "Frije", en: "Refrigerator" },
  pvc: { am: "ፒቪሲ", rom: "PVC", en: "PVC" },
  pvcplpe: { am: "ፒቪሲ ቧንቧ", rom: "PVC Buwanbuwa", en: "PVC pipe" },
  mashgeyafestal: { am: "ማሸጊያ ፌስታል", rom: "Mashegiya Festal", en: "Packaging plastic bag" },
  mashegyafestal: { am: "ማሸጊያ ፌስታል", rom: "Mashegiya Festal", en: "Packaging plastic bag" },
  mashgyafestal: { am: "ማሸጊያ ፌስታል", rom: "Mashegiya Festal", en: "Packaging plastic bag" },
  sesfestal: { am: "ፌስታል", rom: "Festal", en: "Plastic bag" },
  bureshe: { am: "ብሩሽ", rom: "Brush", en: "Brush" },
  buresh: { am: "ብሩሽ", rom: "Brush", en: "Brush" },
  contactor: { am: "ኮንታክተር", rom: "Contactor", en: "Electrical contactor" },
  contacor: { am: "ኮንታክተር", rom: "Contactor", en: "Electrical contactor" },
  meramarate: { am: "ማርማላዳ", rom: "Marmalade", en: "Marmalade" },
  marmarata: { am: "ማርማላዳ", rom: "Marmalade", en: "Marmalade" },
  yeejebateri: { am: "የእጅ ባትሪ", rom: "Ye Ej Battery", en: "Handheld battery" },
  yeejebater: { am: "የእጅ ባትሪ", rom: "Ye Ej Battery", en: "Handheld battery" },
  yegdgdaget: { am: "የግድግዳ ጌጥ", rom: "Ye Gidgida Get", en: "Ye Gidgida Get" },
  yegdedaget: { am: "የግድግዳ ጌጥ", rom: "Ye Gidgida Get", en: "Ye Gidgida Get" },
  a4kaki: { am: "ኤ4 ካኪ", rom: "A4 Kaki", en: "A4 kraft paper" },
  a5kaki: { am: "ኤ5 ካኪ", rom: "A5 Kaki", en: "A5 kraft paper" },
  kakipost: { am: "ካኪ ፖስት", rom: "Kaki Post", en: "Kraft postcard / kraft sheet" },
  acacia: { am: "አካሲያ", rom: "Acacia", en: "Acacia" },
  atakini: { am: "አታኪኒ", rom: "Atakini", en: "Clothes peg" },
  brchkowereket: { am: "ብርጭቆ ወረቀት", rom: "Birchiko Wereket", en: "Glass paper" },
  chinga: { am: "ጭንጋ", rom: "Chinga", en: "Binding wire" },
  yechenamisemare: { am: "የጨንጋ ምስማር", rom: "Ye Chinga Mismar", en: "Wire nail" },
  otes: { am: "ኦትስ", rom: "Oats", en: "Oats" },
  pickup: { am: "ፒክ አፕ", rom: "Pick Up", en: "Pick-up" },
  h20proofabrassive: { am: "ኤች2ኦፒ አብሬሲቭ", rom: "H2OP Abrasive", en: "H2OP abrasive" },
  h20proofabrasive: { am: "ኤች2ኦፒ አብሬሲቭ", rom: "H2OP Abrasive", en: "H2OP abrasive" },
  kirromgetvalue: { am: "ክሮም ጌት ቫልቭ", rom: "Chrome Gate Valve", en: "Chrome gate valve" },
  kiromgetvalue: { am: "ክሮም ጌት ቫልቭ", rom: "Chrome Gate Valve", en: "Chrome gate valve" },
  getvalve: { am: "ጌት ቫልቭ", rom: "Gate Valve", en: "Gate valve" },
  gatevalve: { am: "ጌት ቫልቭ", rom: "Gate Valve", en: "Gate valve" },
  riftvalue: { am: "ሪፍት ቫልቭ", rom: "Rift Valve", en: "Relief valve" },
  nbchecolate: { am: "ኤንቢ ቸኮሌት", rom: "NB Chocolate", en: "NB chocolate" },
  nbchocolat: { am: "ኤንቢ ቸኮሌት", rom: "NB Chocolate", en: "NB chocolate" },
  pizzatakeawaybox: { am: "የፒዛ ቴካዌይ ሳጥን", rom: "Ye Pizza Tekawey Satin", en: "Pizza takeaway box" },
  pizzatakawybox: { am: "የፒዛ ቴካዌይ ሳጥን", rom: "Ye Pizza Tekawey Satin", en: "Pizza takeaway box" },
  terminal: { am: "ተርሚናል", rom: "Terminal", en: "Electrical terminal" },
  terminale: { am: "ተርሚናል", rom: "Terminal", en: "Electrical terminal" },
  terminals: { am: "ተርሚናል", rom: "Terminal", en: "Electrical terminal" },
  terminalsf: { am: "ተርሚናል", rom: "Terminal", en: "Electrical terminal" },
  inbox: { am: "ኢን ቦክስ", rom: "IN Box", en: "Epoxy steel box" },
  inboxusaepoxysteel: { am: "ኢን ቦክስ ኢፖክሲ", rom: "IN Box Epoxy", en: "USA epoxy steel" },
  usaepoxysteel: { am: "ዩኤስኤ ኢፖክሲ ስቲል", rom: "USA Epoxy Steel", en: "USA epoxy steel" },
  h2op50wlamp: { am: "ኤች2ኦፒ ላምፕ", rom: "H2OP Lamp", en: "H2OP 50W lamp" },
  h2op30wlamp: { am: "ኤች2ኦፒ ላምፕ", rom: "H2OP Lamp", en: "H2OP 30W lamp" },
  h2oplampholder: { am: "ኤች2ኦፒ የላምፕ ማስቀመጫ", rom: "H2OP Lamp Holder", en: "H2OP lamp holder" },
  h2oplumpampole: { am: "ኤች2ኦፒ አምፖል", rom: "H2OP Ampole", en: "H2OP bulb" },
  h2opchacklama: { am: "ኤች2ኦፒ ቻክ ላምፕ", rom: "H2OP Chuck Lamp", en: "H2OP chuck lamp" },
  h2oppowderpaint: { am: "ኤች2ኦፒ ፓውደር ቀለም", rom: "H2OP Powder Paint", en: "H2OP powder paint" },
  h2opnastro: { am: "ኤች2ኦፒ ናስትሮ", rom: "H2OP Nastro", en: "H2OP tape" },
  h2opdoorlock: { am: "ኤች2ኦፒ የበር መቆለፊያ", rom: "H2OP Door Lock", en: "H2OP door lock" },
  h20waterproof: { am: "ኤች2ኦ ዋተርፕሩፍ", rom: "H2O Waterproof", en: "H2O waterproof" },
  coldglaze: { am: "ኮልድ ግሌዝ", rom: "Cold Glaze", en: "Cold glaze" },
  glaz: { am: "ግሌዝ", rom: "Glaze", en: "Glaze" },
  fondant: { am: "ፎንዳንት", rom: "Fondant", en: "Fondant" },
  confert: { am: "ኮንፈቲ", rom: "Confetti", en: "Confetti / sprinkles" },
  checolatecheps: { am: "ቸኮሌት ቺፕስ", rom: "Chocolate Chips", en: "Chocolate chips" },
  smallcandy: { am: "ትንሽ ከረሜላ", rom: "Tinish Keremela", en: "Small candy" },
  orderpaper: { am: "የኦርደር ወረቀት", rom: "Ye Order Wereket", en: "Order paper" },
  notepad: { am: "ኖት ፓድ", rom: "Note Pad", en: "Note pad" },
  notepade: { am: "ኖት ፓድ", rom: "Note Pad", en: "Note pad" },
  sticker: { am: "ስቲከር", rom: "Sticker", en: "Sticker" },
  converter: { am: "ኮንቨርተር", rom: "Converter", en: "Converter" },
  conector: { am: "ኮኔክተር", rom: "Connector", en: "Connector" },
  switch: { am: "ስዊች", rom: "Switch", en: "Switch" },
  doublesocket: { am: "ድርብ ሶኬት", rom: "Double Socket", en: "Double socket" },
  pluge: { am: "ፕላግ", rom: "Plug", en: "Plug" },
  electricwire: { am: "የኤሌክትሪክ ሽቦ", rom: "Ye Electric Shibo", en: "Electric wire" },
  electricalmainten: { am: "የኤሌክትሪክ ጥገና", rom: "Ye Electric Tigena", en: "Electrical maintenance" },
  electroied: { am: "ኤሌክትሮድ", rom: "Electrode", en: "Welding electrode" },
  hdmicabel: { am: "ኤችዲኤምአይ ኬብል", rom: "HDMI Cable", en: "HDMI cable" },
  wifiantena: { am: "ዋይፋይ አንቴና", rom: "Wifi Antenna", en: "Wi-Fi antenna" },
  windohandel: { am: "የመስኮት መያዣ", rom: "Ye Meskot Meyazha", en: "Window handle" },
  cabinethandle: { am: "የካቢኔት መያዣ", rom: "Ye Cabinet Meyazha", en: "Cabinet handle" },
  dividers: { am: "ዲቫይደር", rom: "Divider", en: "Divider" },
  divider: { am: "ዲቫይደር", rom: "Divider", en: "Divider" },
  ganch: { am: "ጋንች", rom: "Ganch", en: "Hook" },
  gonte: { am: "ጎንቴ", rom: "Gonte", en: "Gonte" },
  kenet: { am: "ቅንጥ", rom: "Qinṭ", en: "Clip / fastener" },
  kunetale: { am: "ቁንጣሌ", rom: "Quntale", en: "Padlock" },
  morale: { am: "ሞራሌ", rom: "Morale", en: "Morale" },
  ocha: { am: "ኦጫ", rom: "Ocha", en: "Ocha" },
  oche: { am: "ኦጬ", rom: "Oche", en: "Oche" },
  qak: { am: "ቃቅ", rom: "Qaq", en: "Qaq" },
  sefon: { am: "ሰፎን", rom: "Sefon", en: "Sefon sponge" },
  sefonmastesh: { am: "ሰፎን", rom: "Sefon", en: "Sefon sponge" },
  shanti: { am: "ሻንቲ", rom: "Shanti", en: "Shanti" },
  smartpowder: { am: "ስማርት ፓውደር", rom: "Smart Powder", en: "Smart powder detergent" },
  bluebead: { am: "ብሉ ቢድ", rom: "Blue Bead", en: "Blue bead detergent" },
  viks: { am: "ቪክስ", rom: "Vicks", en: "Vicks" },
  coatcofya: { am: "ኮት እና ቆፋያ", rom: "Coat Na Qofaya", en: "Coat and hood" },
  bahlawilebs: { am: "ባህላዊ ልብስ", rom: "Bahilawi Lebs", en: "Traditional clothes" },
  medaberya: { am: "መደበሪያ", rom: "Medeberiya", en: "Shelf / rack" },
  mesetawute: { am: "መስታወት", rom: "Mestawet", en: "Mirror / glass" },
  metasha: { am: "መታሻ", rom: "Metasha", en: "Pillow" },
  mekese: { am: "መቀስ", rom: "Meqes", en: "Scissors" },
  knifegebeta: { am: "ቢላ ገበታ", rom: "Bila Gebeta", en: "Cutting board knife set" },
  rawerheadl: { am: "ራወር ሄድል", rom: "Rower Handle", en: "Drawer handle" },
  pistonchin: { am: "ፒስቶን", rom: "Piston", en: "Piston" },
  kolonet: { am: "ኮሎኔት", rom: "Colonet", en: "Colonet" },
  korkoro: { am: "ቆርቆሮ", rom: "Qorqoro", en: "Corrugated iron / tin" },
  gouder: { am: "ጎደር", rom: "Gouder", en: "Gutter" },
  wenfite: { am: "ወንፊት", rom: "Wenfite", en: "Sieve / colander" },
  fayezet: { am: "ፋየዝት", rom: "Fayezet", en: "Fayezet" },
  fayzit: { am: "ፋየዝት", rom: "Fayezet", en: "Fayezet" },
  furesheka: { am: "ፍሬሽካ", rom: "Freshka", en: "Freshka" },
  bite: { am: "ቢት", rom: "Bite", en: "Bite snack" },
  gold: { am: "ጎልድ", rom: "Gold", en: "Gold" },
  goldleble: { am: "ጎልድ ሌብል", rom: "Gold Label", en: "Gold Label" },
  materialspringwash: { am: "ስፕሪንግ ዋሽ", rom: "Spring Wash", en: "Spring wash material" },
  changecmosbattery: { am: "ሲሞስ ባትሪ", rom: "CMOS Battery", en: "CMOS battery" },
  chargerservice: { am: "ቻርጀር ሰርቪስ", rom: "Charger Service", en: "Charger service" },
  perterservice: { am: "ፕሪንተር ሰርቪስ", rom: "Printer Service", en: "Printer service" },
  yedesservise: { am: "የዴሽ ሰርቪስ", rom: "Ye Desh Service", en: "Dish service" },
  feregemaintenase: { am: "የፍሪጅ ጥገና", rom: "Ye Frije Tigena", en: "Fridge maintenance" },
  maitenance: { am: "ጥገና", rom: "Tigena", en: "Maintenance" },
  eltradea3machine: { am: "ኤልትሬድ ኤ3 ማሽን", rom: "Eltrade A3 Machine", en: "Eltrade A3 machine" },
  nanodas17a: { am: "ናኖዳስ 17ኤ", rom: "Nanodas 17A", en: "Nanodas 17A toner" },
  nanodas: { am: "ናኖዳስ", rom: "Nanodas", en: "Nanodas" },
  toner42ahp: { am: "ቶነር 42ኤ ኤችፒ", rom: "Toner 42A HP", en: "HP 42A toner" },
  toner85a: { am: "ቶነር 85ኤ", rom: "Toner 85A", en: "85A toner" },
  toner83a: { am: "ቶነር 83ኤ", rom: "Toner 83A", en: "83A toner" },
  vartalonglifeaabli: { am: "ቫርታ ባትሪ", rom: "Varta Battery", en: "Varta long life AA" },
  yerumberbatterydingay: { am: "የሮም ባትሪ ድንጋይ", rom: "Ye Rom Battery Dingay", en: "Remote battery cell" },
  yemausedengaye: { am: "የማውስ ድንጋይ", rom: "Ye Mouse Dingay", en: "Mouse battery cell" },
  yemayekdengay: { am: "የማየክ ድንጋይ", rom: "Ye Mayek Dingay", en: "Remote battery cell" },
  roto: { am: "ሮቶ", rom: "Roto", en: "Roto tank" },
  telekuroto: { am: "ትልቁ ሮቶ", rom: "Tilku Roto", en: "Large roto tank" },
  pasetal: { am: "ፕላስቲክ", rom: "Plastic", en: "Plastic" },
  pasetale: { am: "ፕላስቲክ", rom: "Plastic", en: "Plastic" },
  pastale: { am: "ፕላስቲክ", rom: "Plastic", en: "Plastic" },
  pasetaleteleku: { am: "ትልቁ ፕላስቲክ", rom: "Tilku Plastic", en: "Large plastic" },
  pasetaletenshu: { am: "ትንሹ ፕላስቲክ", rom: "Tinshu Plastic", en: "Small plastic" },
  tekuerpasetale: { am: "ጥቁር ፕላስቲክ", rom: "Tikur Plastic", en: "Black plastic" },
  tikurpestal: { am: "ጥቁር ፕላስቲክ", rom: "Tikur Plastic", en: "Black plastic" },
  takeawayaluminumfoodbox: {
    am: "የቴካዌይ አሉሚኒየም ሳጥን",
    rom: "Ye Tekawey Aluminium Satin",
    en: "Takeaway aluminium food box",
  },
  tortacaketakeawaybox: {
    am: "የቶርታ ኬክ ቴካዌይ ሳጥን",
    rom: "Ye Torta Cake Tekawey Satin",
    en: "Torta cake takeaway box",
  },
  kipmahtem: { am: "ክብ ማህተም", rom: "Kib Mahtem", en: "Round stamp" },
  titormahtem: { am: "ጥቁር ማህተም", rom: "Tikur Mahtem", en: "Stamp" },
  bilpaper: { am: "የቢል ወረቀት", rom: "Ye Bil Wereket", en: "Bill paper" },
  tedrateworkate: { am: "ተደራራቢ ወረቀት", rom: "Tederarabi Wereket", en: "Carbonless paper" },
  yemesemrwuha: { am: "የመስመር ውሃ", rom: "Ye Mesmer Wuha", en: "Line / tap water fitting" },
  yekebamateleya: { am: "የቅቤ ማቅለጫ", rom: "Ye Kibe Maqelcha", en: "Butter melter" },
  chipudbale: { am: "ቺፑድ ባለ", rom: "Chipud Bale", en: "Chipboard sheet" },
  mdfbale: { am: "ኤምዲኤፍ ባለ", rom: "MDF Bale", en: "MDF sheet" },
  kachabite: { am: "ካቻቢት", rom: "Kachabit", en: "Kachabit" },
  fd: { am: "ኤፍዲ", rom: "FD", en: "FD fitting" },
  rolchickler: { am: "ሮል ቺክለር", rom: "Roll Chickler", en: "Roll chiller" },
  h2op50wlamp: { am: "ኤች2ኦፒ 50ዋት ላምፕ", rom: "H2OP 50W Lamp", en: "H2OP 50W lamp" },
  h2op30wlamp: { am: "ኤች2ኦፒ 30ዋት ላምፕ", rom: "H2OP 30W Lamp", en: "H2OP 30W lamp" },
  inbox: { am: "ኢን ቦክስ", rom: "IN Box", en: "IN box epoxy steel" },
  kachabitekutr: { am: "ካቻቢት", rom: "Kachabit", en: "Kachabit" },
  h20proofabrassive: { am: "ኤች2ኦፒ አብሬሲቭ", rom: "H2OP Abrasive", en: "H2OP abrasive" },
  h20proofabrasive: { am: "ኤች2ኦፒ አብሬሲቭ", rom: "H2OP Abrasive", en: "H2OP abrasive" },
  debtergets: { am: "ደብተር", rom: "Debter", en: "Exercise book" },
  decor: { am: "ዲኮር", rom: "Decor", en: "Decor" },
  doubleaa4paper: { am: "ድርብ ኤ4 ወረቀት", rom: "Double A4 Wereket", en: "Double A4 paper" },
  ejata: { am: "እጃታ", rom: "Ejata", en: "Hand tool / ejata" },
  gebsekolobelowze: { am: "ገብስ ቆሎ በሎውዝ", rom: "Gebs Kolo Belowze", en: "Barley kolo Belowze" },
  h20waterproof: { am: "ኤች2ኦ ዋተርፕሩፍ", rom: "H2O Waterproof", en: "H2O waterproof" },
  h20proofampole: { am: "ኤች2ኦፒ አምፖል", rom: "H2OP Ampole", en: "H2OP waterproof bulb" },
  insulatingtape: { am: "ኢንሱሌቲንግ ቴፕ", rom: "Insulating Tape", en: "Insulating tape" },
  kentmegazinerag: { am: "ኬንት መጽሔት ጨርቅ", rom: "Kent Magazine Rag", en: "Magazine rag" },
  largeshoppingbag: { am: "ትልቅ የሸመታ ከረጢት", rom: "Tilq Ye Shemeta Keretit", en: "Large shopping bag" },
  teketaybercheko: { am: "ተከታይ ብርጭቆ", rom: "Teketay Birchiko", en: "Stacking glass" },
  zebib: { am: "ዘቢብ", rom: "Zebib", en: "Raisins" },
  foset: { am: "ፎሴት", rom: "Faucet", en: "Faucet / tap" },
  foseter: { am: "ፎስተር", rom: "Foster", en: "Foster beer" },
  gordengin: { am: "ጎርደን ጂን", rom: "Gordon Gin", en: "Gordon's gin" },
  inboxusaepoxysteel: { am: "ኢን ቦክስ ኢፖክሲ ስቲል", rom: "IN Box Epoxy Steel", en: "IN box USA epoxy steel" },
  kesher: { am: "ቀሸር", rom: "Kesher", en: "Peel / rind" },
  ketam: { am: "ከታም", rom: "Ketam", en: "Ketam" },
  blackcoopolivebig: { am: "ጥቁር ኦሊቭ", rom: "Tikur Olive", en: "Black olive (large)" },
  beefmortadellamozerellachesse: {
    am: "የበሬ ሞርታዴላ ሞዘሬላ",
    rom: "Ye Bere Mortadella Mozzarella",
    en: "Beef mortadella with mozzarella",
  },
};

// Recommended registration/purchase/recipe options (fill lexicon gaps; do not overwrite existing).
for (const [core, triple] of Object.entries(recommendedCoresToByCore())) {
  if (!BY_CORE[core]) BY_CORE[core] = triple;
}

/**
 * Phrase-level overrides checked against normalized full name (before letterCore).
 * Longer / more specific phrases should be listed first in matching logic.
 * @type {Array<{ re: RegExp, triple: CrystalTriple }>}
 */
export const BY_PHRASE = [
  // Packaging / plastics (before generic pasta/pasta-like cores)
  {
    re: /\b(poreshen|poresen|porshen|portion)\s+(pasetale|pesetale|pestal|pesatale|pestale|plastic|festal)\b/,
    triple: BY_CORE.portionplastic,
  },
  {
    re: /\b(tekawey|tekawy|takawy|tekeawey|teakawey)\s+(pasetale|pesetale|pestal|pestale|pastale|box)\b/,
    triple: BY_CORE.tekaweypesetale,
  },
  { re: /\bpizza\s+takeaway\s+box\b|\bpizza\s+takawy\s+box\b/, triple: BY_CORE.pizzatakeawaybox },
  { re: /\btakeaway\s+box\b|\bteakawey\s+box\b/, triple: BY_CORE.takeawaybox },
  { re: /\bpizza\s+box\b/, triple: BY_CORE.pizzabox },
  { re: /\bcake\s+box\b/, triple: BY_CORE.cakebox },
  { re: /\bfile\s+box\b|\bbox\s+file\b/, triple: BY_CORE.filebox },
  { re: /\bmash(e)?n\s+paper\b|\bmashein\s+paper\b/, triple: BY_CORE.mashenpaper },
  { re: /\b(telku|tilku)\s+festal\b/, triple: BY_CORE.telkufestal },
  { re: /\b(tenshu|tinshu)\s+festal\b/, triple: BY_CORE.tenshufestal },
  { re: /\bmash(ge|egy|gy)a\s+festal\b/, triple: BY_CORE.mashgeyafestal },
  { re: /\bslinder\s+gas\b|\bsilder\s*\(?\s*lp\s*\)?\s*gas\b/, triple: BY_CORE.slindergas },
  { re: /\bangle\s+val[uv]e\b/, triple: BY_CORE.anglevalue },
  { re: /\bgate\s+val[uv]e\b|\bget\s+val[uv]e\b/, triple: BY_CORE.gatevalve },
  { re: /\bcaptain\s+order\b|\bcapetan\s+order\b|\bcapitain\s+order\b|\bcaptan\s+order\b/, triple: BY_CORE.capetanorder },
  { re: /\bair\s*fr(?:e|a)sh(?:ener)?\b|\bairfrash\b/, triple: BY_CORE.airfresh },
  { re: /\bshanti\s+cream\b/, triple: BY_CORE.shanticream },
  { re: /\bfood\s+colou?r\s+yellow\b/, triple: BY_CORE.foodcolouryellow },
  { re: /\bfood\s+colou?r\s+red\b/, triple: BY_CORE.foodcolourred },
  { re: /\bfood\s+colou?r\b/, triple: BY_CORE.foodcolour },
  { re: /\btoilet\s+soft\b/, triple: BY_CORE.toiletsoft },
  { re: /\broll\s+soft\b/, triple: BY_CORE.soft },
  { re: /\bsoya\s+souce\b|\bsoy\s+souce\b|\bsoya\s+sauce\b|\bsoy\s+sauce\b/, triple: BY_CORE.soyasouce },
  { re: /\bdark\s+soya\b/, triple: BY_CORE.darksoya },
  { re: /\blight\s+soya\b/, triple: BY_CORE.lightsoya },
  { re: /\bchecolate\s+syrup\b|\bchocolat?e\s+syrup\b|\bchecolet\s+srape\b/, triple: BY_CORE.checolatesyrup },
  { re: /\bcash\s+ri[dg]ister\s+(roll|paper)\b/, triple: BY_CORE.cashridisterroll },
  { re: /\breceipts?\s+ncr\b/, triple: BY_CORE.receiptsncr },
  { re: /\bye\s+eje\s+bateri?\b/, triple: BY_CORE.yeejebateri },
  { re: /\bye\s+gdgda\s+get\b|\byegdeda\s+get\b/, triple: BY_CORE.yegdgdaget },
  { re: /\ba4\s+kaki\b/, triple: BY_CORE.a4kaki },
  { re: /\ba5\s+kaki\b/, triple: BY_CORE.a5kaki },
  { re: /\bbrchko\s+wereket\b/, triple: BY_CORE.brchkowereket },
  { re: /\bsuper\s+gato\b/, triple: BY_CORE.supergato },
  { re: /\bshut\s+up\b/, triple: BY_CORE.shutup },
  { re: /\bpick\s+up\b/, triple: BY_CORE.pickup },
  { re: /\bmesherum\s+big\b/, triple: BY_CORE.mesherumbig },
  { re: /\bberkeni\b/, triple: BY_CORE.berkeni },
  { re: /\btakeaway\s+alumini?um\s+food\s+box\b/, triple: BY_CORE.takeawayaluminumfoodbox },
  { re: /\btoni?er\s*83\s*a\b|\btoner83a\b/, triple: BY_CORE.toner83a },
  { re: /\blexi\s+eskerb(?:ito|erto)\b/, triple: BY_CORE.lexieskerbito },
  { re: /\bketchup\s+jarican\b/, triple: { am: "ኬጨፕ ጀሪካን", rom: "Ketchup Jerican", en: "Ketchup jerrycan" } },
  { re: /\bmareker\b/, triple: { am: "ማርከር", rom: "Marker", en: "Marker" } },
  { re: /\bmashegeya\b/, triple: { am: "ማሸጊያ", rom: "Mashegiya", en: "Packaging material" } },
  { re: /\boil\s+5\s*k\.?\s*g\b/, triple: BY_CORE.oil },
  { re: /^toilet$/, triple: { am: "ሽንት ቤት", rom: "Shint Bet", en: "Toilet" } },
  { re: /^ketma$|^ketam$/, triple: { am: "ከታም", rom: "Ketam", en: "Ketam" } },

  { re: /\bh2op\s+tinner\b|\bh20p\s+tinner\b/, triple: BY_CORE.h2optinner },
  { re: /\bh2op\s*50\s*w\s*lamp\b/, triple: BY_CORE.h2op50wlamp },
  { re: /\bh2op\s*30\s*w\s*lamp\b/, triple: BY_CORE.h2op30wlamp },
  { re: /\bin\s*box\b/, triple: BY_CORE.inbox },
  { re: /\bh20\s*proof\s+abrass?ive\b|\bh20proof\s+abrass?ive\b/, triple: BY_CORE.h20proofabrasive },
  { re: /\bh20\s*water\s*proof\b/, triple: BY_CORE.h20waterproof },
  { re: /\bh20proof\b(?!\s*abrass?ive)/, triple: BY_CORE.h20waterproof },
  { re: /\binsulating\s+tape\b/, triple: BY_CORE.insulatingtape },
  { re: /\blarge\s+shopping\s+bag\b/, triple: BY_CORE.largeshoppingbag },
  { re: /\bgebse\s+kolo\b|\bgebs\s+kolo\b/, triple: BY_CORE.gebsekolobelowze },
  { re: /\bzebib\b/, triple: BY_CORE.zebib },
  { re: /\bgorden\s+gin\b|\bgordon\s+gin\b/, triple: BY_CORE.gordengin },
  { re: /\bdouble\s+aa?4\s+paper\b/, triple: BY_CORE.doubleaa4paper },
  { re: /\bteketay\s+bercheko\b/, triple: BY_CORE.teketaybercheko },

  { re: /\bberger\s+dabo\b/, triple: BY_CORE.bergerdabo },
  { re: /\bgradia\b.*\bonion\b|\bwhite\s+onion\b/, triple: BY_CORE.gradiawhiteonion },
  { re: /\bbaro\s+shenkuret\b/, triple: BY_CORE.baroshenkuret },
  { re: /\bnech\s+shenkuret\b/, triple: BY_CORE.nechshenkuret },
  { re: /\bkey\s*shnkurt\b|\bkey\s+shenkurt\b/, triple: BY_CORE.keyshnkurt },
  { re: /\bambo\s+wuha\b|\bambo\s+water\b/, triple: BY_CORE.ambowuha },
  { re: /\bpeanut\s+butt?er\b/, triple: BY_CORE.peanuthbutter },
  { re: /\btomato\s+pasta\b/, triple: BY_IDENTITY.tomato_pasta },
  { re: /\btomato\s+peste\b|\btomato\s+pest\b|\btomato\s+paste\b/, triple: BY_IDENTITY.tomato_paste },
  { re: /\bcooking\s+oil\b/, triple: BY_CORE.cookingoil },
  { re: /\bsun\s*flower\s+oil\b/, triple: BY_CORE.sunfloweroil },
  { re: /\bpalm\s+oil\b/, triple: BY_CORE.palmoil },
  { re: /\bwheat\s+flour\b/, triple: BY_IDENTITY.wheat_flour },
  { re: /\bwhite\s+flour\b/, triple: BY_IDENTITY.white_flour },
  { re: /\bcoffee\s+powder\b/, triple: BY_IDENTITY.coffee_powder },
  { re: /\b(coffee|coffe)\s+cups?\b/, triple: BY_IDENTITY.coffee_cup },
  { re: /\b(addis|adis)\s+tea\s+bags?\b/, triple: BY_IDENTITY.addis_tea_bag },
  { re: /\b(addis|adis)\s+tea\b/, triple: BY_IDENTITY.addis_tea },
  { re: /\btea\s+bags?\b/, triple: BY_CORE.teabag },
  { re: /\bgreen\s+tea\s+bags?\b/, triple: BY_CORE.greenteabag },
  { re: /\bgreen\s+tea\b/, triple: BY_CORE.greentea },
  { re: /\b(esetaprale|setapelare|esteplar|estepler)\s+(shbo|shebo|shibo)\b/, triple: BY_IDENTITY.esteplar_shbo },
  { re: /\beka\s+mateb[aei]ya\s+sh[ei]?bo\b/, triple: BY_IDENTITY.shbo_cleaning },
  {
    re: /\b(ye\s*)?(shro|shero|shiro|yeshro)\s+bakela\b/,
    triple: BY_IDENTITY.shiro_bakela,
  },
  {
    re: /\b(ye\s*)?(shro|shero|shiro|yeshro)\s+ater\b/,
    triple: BY_IDENTITY.shiro_ater,
  },
  { re: /\bmtn\s+(shro|shero|shiro)\b/, triple: BY_IDENTITY.shiro_mtn },
  { re: /\binjera\s+plastic\b|\benjera\s+lasetic\b/, triple: BY_CORE.injeraplastic },
  { re: /\benergy\s+saving\s+lamp\b/, triple: { am: "ኢነርጂ ሴቪንግ ላምፕ", rom: "Energy Saving Lamp", en: "Energy saving lamp" } },
  { re: /\btoilet\s+cleaner\b/, triple: BY_CORE.toiletcleaner },
  { re: /\bwindow\s+cleaner\b/, triple: BY_CORE.windowcleaner },
  { re: /\bliquid\s+soap\b/, triple: BY_CORE.liquidsoap },
  { re: /\bdish\s+wash(ing)?\b/, triple: BY_CORE.dishwashing },
  { re: /\bcopy\s+paper\b|\bcopy\s+werket\b/, triple: BY_CORE.copypaper },
  { re: /\ba4\s+paper\b/, triple: BY_CORE.a4paper },
  { re: /\bbaking\s+paper\b|\bbackig\s+paper\b/, triple: BY_CORE.bakingpaper },
  { re: /\balmunium\s+foil\b|\baluminium\s+foil\b|\baluminum\s+foil\b/, triple: BY_CORE.almuniumfoil },
  { re: /\bplastic\s+foil\b/, triple: BY_CORE.plasticfoil },
  { re: /\b(soft\s+dr(?:i|ie|in)nk\s+)?pep[si]{1,2}\b|\bsoft\s+dirnk\s+pepis\b|\bpepis\b/, triple: BY_CORE.softdirnkpepis },
  { re: /\bsoft\s+drink\s+mirinda\b|\bsoft\s+drink\s+mirnda\b/, triple: BY_CORE.softdrinkmirnda },
  { re: /\bsoft\s+drink\s+coca\b/, triple: BY_CORE.softdrinkcoca },
  { re: /\bsoft\s+drink\b|\bsoft\s+drike\b|\bsoft\s+dirnk\b/, triple: BY_CORE.softdrink },
  { re: /\bcoca\s+cola\b/, triple: BY_CORE.cocacola },
  { re: /\bgarlic\b/, triple: BY_IDENTITY.garlic_bulb },
  { re: /\bnech\s+shenkurt\b|\bnech\s+shenkuret\b|\bnech\s+senkuret\b/, triple: BY_IDENTITY.white_onion },
  { re: /\bakezha\b|\bakeja\b/, triple: BY_CORE.akezha },
  { re: /\bbelewa\s+ye\s+atekelte\b|\bbelewa\s+ye\s+atkilt\b/, triple: BY_CORE.belawayeatekelte },
  { re: /\bbelewa\b/, triple: BY_CORE.belewa },
  { re: /\bbath\s+soap\b/, triple: BY_CORE.bathsoap },
  { re: /\bhand\s+wash\b/, triple: BY_CORE.handwash },
  { re: /\bdoor\s+lock\b/, triple: BY_CORE.doorlock },
  { re: /\bflash\s+disk\b/, triple: BY_CORE.flashdisk },
  { re: /\bnote\s+book\b/, triple: BY_CORE.notebook },
  { re: /\bnote\s+pade?\b/, triple: BY_CORE.notepad },
  { re: /\bt[\s-]?shirt\b/, triple: BY_CORE.tshirt },
  { re: /\bskin?\s*off\b|\bsmi\s+off\b|\bsmirn\s+off\b/, triple: { am: "ስሚርኖፍ", rom: "Smirnoff", en: "Smirnoff" } },
];

/**
 * Strip station / size noise from letter cores for lexicon lookup.
 * @param {string} core
 */
export function normalizeCoreForLexicon(core) {
  return String(core || "")
    .toLowerCase()
    .replace(/(staff|kitchen|bar|barista|chef)$/g, "")
    .replace(/^(ye|yee)/, "ye")
    .trim();
}

/**
 * Exact then near-match lexicon lookup.
 * @param {string} core
 * @param {(a: string, b: string) => number} [distanceFn]
 * @returns {CrystalTriple | null}
 */
export function lookupCoreTriple(core, distanceFn) {
  if (!core) return null;
  const c = normalizeCoreForLexicon(core);
  if (BY_CORE[c]) return BY_CORE[c];
  if (BY_CORE[core]) return BY_CORE[core];

  // Near-match only for reasonably long cores (avoid merging short confusables)
  if (!distanceFn || c.length < 6) return null;
  let best = null;
  let bestDist = 3;
  for (const key of Object.keys(BY_CORE)) {
    if (Math.abs(key.length - c.length) > 2) continue;
    if (key.length < 6) continue;
    const d = distanceFn(c, key);
    if (d < bestDist || (d === bestDist && key.length > (best?.key.length || 0))) {
      bestDist = d;
      best = { key, triple: BY_CORE[key] };
    }
  }
  if (best && bestDist <= 1) return best.triple;
  return null;
}

export function formatCrystalTriple(triple, sizeSuffix = "") {
  const en = sizeSuffix ? `${triple.en}${sizeSuffix}` : triple.en;
  return `${triple.am}|${triple.rom}|${en}`;
}

/**
 * Title-case English fallback when no lexicon hit.
 * Still uses pipe format: —|RomanizedGuess|English
 */
export function englishOnlyCrystal(display) {
  const titled = display
    .split("/")
    .map((part) =>
      part
        .trim()
        .split(/\s+/)
        .map((w) =>
          w.length <= 2
            ? w.toUpperCase()
            : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase(),
        )
        .join(" "),
    )
    .join("/");
  return `—|${titled}|${titled}`;
}

/**
 * Extract trailing size / qty phrase to append to English meaning.
 * e.g. "oil 5 liter" → " 5 liter"
 */
export function extractSizeSuffix(normalized) {
  const m = normalized.match(
    /\s+(\d+(?:\.\d+)?(?:\s*[x×]\s*\d+(?:\.\d+)?)?(?:\s*(?:l|lt|ltr|liter|litre|kg|g|ml|cl|pcs|pc|pack|box|bottle|bag|cup|dozen|roll|sheet|unit|w|watt))?)\s*$/i,
  );
  if (!m) return "";
  return ` ${m[1].replace(/\s+/g, " ").trim()}`;
}
